import React, { useState } from 'react';
import {
  Receipt,
  ShieldCheck,
  Download,
  Search,
  Filter,
  Building2,
  Calendar,
  CheckCircle2,
  Clock,
  ArrowUpRight,
  ArrowDownLeft,
  X,
  CreditCard,
  Plus,
  Lock,
  ExternalLink,
  Copy,
  Check,
} from 'lucide-react';
import { DistributorEscrowPayment, DistributorProfileData } from '../../types';
import { INITIAL_DISTRIBUTOR_PROFILE } from '../../mockData';

interface DistributorPaymentsScreenProps {
  escrowPayments?: DistributorEscrowPayment[];
  profile?: DistributorProfileData;
  onDepositEscrow: (payment: Partial<DistributorEscrowPayment>) => void;
}

export const DistributorPaymentsScreen: React.FC<DistributorPaymentsScreenProps> = ({
  escrowPayments = [],
  profile = INITIAL_DISTRIBUTOR_PROFILE,
  onDepositEscrow,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('All');
  const [isDepositModalOpen, setIsDepositModalOpen] = useState(false);
  const [selectedReceiptPayment, setSelectedReceiptPayment] = useState<DistributorEscrowPayment | null>(null);
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const handleDownloadReceipt = (p: DistributorEscrowPayment) => {
    const receiptContent = `================================================================================
                    PLASTOSHIP GUJARAT B2B INFRASTRUCTURE
                     ESCROW PAYMENT RECEIPT & TAX INVOICE
================================================================================
Receipt No:     REC-${p.id}
Escrow Txn ID:  ${p.id}
Date:           ${p.escrowDepositDate}
Status:         ${p.escrowStatus.toUpperCase()}
Bank UTR:       ${p.utrNumber}
================================================================================
BUYER / DISTRIBUTOR:
Company:        ${profile.companyName}
Distributor ID: ${profile.id}
GSTIN:          ${profile.gstin}
Zone:           ${profile.industrialZone || profile.city}
--------------------------------------------------------------------------------
BENEFICIARY / SUPPLIER:
Manufacturer:   ${p.manufacturerName}
Consignment:    ${p.orderProduct}
Purchase Order: ${p.orderId}
Quantity:       ${p.quantity}
--------------------------------------------------------------------------------
FINANCIAL SETTLEMENT:
Gross Amount:   INR ${p.grossAmount.toLocaleString('en-IN')}
Escrow Release: ${p.escrowStatus}
Payment Route:  Verified Indian Banking Escrow System
================================================================================
Computerized receipt generated by PlastoShip Gujarat Portal.
================================================================================`;

    const blob = new Blob([receiptContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Invoice_Receipt_${p.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // New Deposit Form
  const [depositOrderId, setDepositOrderId] = useState('ORD-GJ-7041');
  const [depositAmount, setDepositAmount] = useState<number>(1500000);
  const [depositMethod, setDepositMethod] = useState<'Razorpay B2B' | 'Virtual Escrow Account' | 'NEFT/RTGS'>('Razorpay B2B');

  const formatINR = (val: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(val);
  };

  const totalDeposits = escrowPayments.reduce((sum, p) => sum + p.grossAmount, 0);
  const activeHeld = escrowPayments
    .filter((p) => p.escrowStatus === 'Funds in Escrow')
    .reduce((sum, p) => sum + p.grossAmount, 0);
  const released = escrowPayments
    .filter((p) => p.escrowStatus === 'Released to Manufacturer')
    .reduce((sum, p) => sum + p.grossAmount, 0);

  const filteredPayments = escrowPayments.filter((p) => {
    const matchesStatus = statusFilter === 'All' || p.escrowStatus === statusFilter;
    const query = (searchQuery || '').toLowerCase().trim();
    if (!query) return matchesStatus;

    const matchesSearch =
      (p.id || '').toLowerCase().includes(query) ||
      (p.orderId || '').toLowerCase().includes(query) ||
      (p.manufacturerName || '').toLowerCase().includes(query) ||
      (p.orderProduct || '').toLowerCase().includes(query) ||
      (p.utrNumber || '').toLowerCase().includes(query);
    return matchesStatus && matchesSearch;
  });

  const copyToClipboard = (text: string, fieldName: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleDepositSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newPayment: Partial<DistributorEscrowPayment> = {
      id: `ESC-GJ-${Math.floor(8100 + Math.random() * 900)}`,
      orderId: depositOrderId,
      orderProduct: 'HDPE Granules / Extrusion Resins',
      manufacturerName: 'Morbi Polymer Extrusions Pvt Ltd',
      quantity: '15 MT',
      grossAmount: depositAmount,
      escrowDepositDate: new Date().toISOString().replace('T', ' ').slice(0, 16),
      escrowStatus: 'Funds in Escrow',
      paymentMethod: depositMethod,
      utrNumber: `UTR-HDFC-${Math.floor(99000000 + Math.random() * 999999)}`,
    };

    onDepositEscrow(newPayment);
    setIsDepositModalOpen(false);
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header Banner */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 bg-white p-6 rounded-2xl border border-[#E2E8F0] shadow-xs">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-xl md:text-2xl font-extrabold text-[#1E293B] tracking-tight">
              PlastoShip Escrow & Payment Vault
            </h2>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-[#6F42C1]/10 text-[#6F42C1] border border-[#6F42C1]/20">
              Bank Escrow Safeguard
            </span>
          </div>
          <p className="text-xs text-[#5A6B82] font-medium">
            Manage your polymer procurement escrow balances, view released settlements, and review UTR confirmations.
          </p>
        </div>

        <button
          type="button"
          onClick={() => setIsDepositModalOpen(true)}
          className="px-4 py-2.5 rounded-xl bg-[#6F42C1] hover:bg-[#5C35A5] text-white text-xs font-bold shadow-xs transition-colors cursor-pointer flex items-center gap-2 self-start lg:self-auto"
        >
          <Plus className="w-4 h-4" />
          <span>Deposit into Escrow</span>
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-2xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[11px] font-bold text-[#5A6B82] uppercase tracking-wider">
            Total Escrow Throughput
          </span>
          <h3 className="text-2xl font-extrabold text-[#1E293B] mt-2">{formatINR(totalDeposits)}</h3>
          <p className="text-xs font-semibold text-[#5A6B82] mt-1">Across all procurement POs</p>
        </div>

        <div className="bg-white rounded-2xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[11px] font-bold text-[#5A6B82] uppercase tracking-wider">
            Active Locked in Escrow
          </span>
          <h3 className="text-2xl font-extrabold text-[#6F42C1] mt-2">{formatINR(activeHeld)}</h3>
          <p className="text-xs font-semibold text-[#6F42C1] mt-1 flex items-center gap-1">
            <Lock className="w-3 h-3" />
            Held safely until delivery QC
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[11px] font-bold text-[#5A6B82] uppercase tracking-wider">
            Released to Plants
          </span>
          <h3 className="text-2xl font-extrabold text-[#5C35A5] mt-2">{formatINR(released)}</h3>
          <p className="text-xs font-semibold text-[#6F42C1] mt-1">Settled after verified delivery</p>
        </div>

        <div className="bg-white rounded-2xl border border-[#E2E8F0] p-5 shadow-xs">
          <span className="text-[11px] font-bold text-[#5A6B82] uppercase tracking-wider">
            Approved Trade Credit Limit
          </span>
          <h3 className="text-2xl font-extrabold text-[#1E293B] mt-2">{profile.creditLimit}</h3>
          <p className="text-xs font-semibold text-[#6F42C1] mt-1">By PlastoShip Finance Desk</p>
        </div>
      </div>

      {/* Escrow Mechanism Explainer Card */}
      <div className="bg-[#5C35A5] rounded-2xl p-6 text-white grid grid-cols-1 md:grid-cols-3 gap-6 relative overflow-hidden">
        <div className="space-y-2">
          <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center text-purple-200 font-bold text-sm">
            1
          </div>
          <h4 className="font-extrabold text-sm text-white">Deposit to Escrow</h4>
          <p className="text-xs text-white/80 leading-relaxed">
            Buyer deposits order funds into PlastoShip ICICI/HDFC Escrow Account upon confirming the order.
          </p>
        </div>

        <div className="space-y-2">
          <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center text-purple-200 font-bold text-sm">
            2
          </div>
          <h4 className="font-extrabold text-sm text-white">Plant Produces & Ships</h4>
          <p className="text-xs text-white/80 leading-relaxed">
            Manufacturer receives guaranteed payment lock, manufactures resin batch, and dispatches truck consignment.
          </p>
        </div>

        <div className="space-y-2">
          <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center text-purple-200 font-bold text-sm">
            3
          </div>
          <h4 className="font-extrabold text-sm text-white">Delivery Verified & Released</h4>
          <p className="text-xs text-white/80 leading-relaxed">
            Once warehouse verifies tare weight and COA quality report, funds are directly credited to the plant&apos;s bank.
          </p>
        </div>
      </div>

      {/* Filters & Search */}
      <div className="bg-white p-4 rounded-2xl border border-[#E2E8F0] shadow-xs flex flex-col sm:flex-row gap-3 items-center justify-between">
        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 text-[#5A6B82] absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search Escrow ID, PO ID, UTR #..."
            className="w-full pl-10 pr-4 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl text-xs font-semibold text-[#1E293B] focus:outline-none focus:border-[#6F42C1]"
          />
        </div>

        <div className="flex items-center gap-2 overflow-x-auto w-full sm:w-auto pb-1 sm:pb-0">
          {['All', 'Funds in Escrow', 'Released to Manufacturer'].map((status) => (
            <button
              key={status}
              type="button"
              onClick={() => setStatusFilter(status)}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors cursor-pointer ${
                statusFilter === status
                  ? 'bg-[#6F42C1] text-white'
                  : 'bg-[#F4F7FC] text-[#5A6B82] hover:text-[#1E293B]'
              }`}
            >
              {status}
            </button>
          ))}
        </div>
      </div>

      {/* Escrow Transactions Table */}
      <div className="bg-white rounded-2xl border border-[#E2E8F0] shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-[#F8FAFC] border-b border-[#E2E8F0] text-[11px] font-bold text-[#5A6B82] uppercase tracking-wider">
                <th className="py-3.5 px-6">Escrow ID</th>
                <th className="py-3.5 px-6">Order / Product</th>
                <th className="py-3.5 px-6">Supplier Plant</th>
                <th className="py-3.5 px-6">Quantity</th>
                <th className="py-3.5 px-6">Escrow Amount</th>
                <th className="py-3.5 px-6">Bank UTR Reference</th>
                <th className="py-3.5 px-6 text-center">Status</th>
                <th className="py-3.5 px-6 text-right">Receipt</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E2E8F0] text-xs font-semibold text-[#1E293B]">
              {filteredPayments.map((p) => (
                <tr key={p.id} className="hover:bg-[#F8FAFC] transition-colors">
                  <td className="py-4 px-6 font-mono font-bold text-[#1E293B]">
                    {p.id}
                    <div className="text-[10px] text-[#5A6B82] font-normal">{p.escrowDepositDate}</div>
                  </td>
                  <td className="py-4 px-6">
                    <div className="font-extrabold text-[#1E293B]">{p.orderProduct}</div>
                    <div className="font-mono text-[11px] text-[#5A6B82]">PO: {p.orderId}</div>
                  </td>
                  <td className="py-4 px-6 font-bold text-[#1E293B]">{p.manufacturerName}</td>
                  <td className="py-4 px-6 font-bold">{p.quantity}</td>
                  <td className="py-4 px-6 font-mono font-bold text-sm text-[#1E293B]">
                    {formatINR(p.grossAmount)}
                  </td>
                  <td className="py-4 px-6 font-mono text-[11px] text-[#5A6B82]">{p.utrNumber}</td>
                  <td className="py-4 px-6 text-center">
                    <span
                      className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold ${
                        p.escrowStatus === 'Funds in Escrow'
                          ? 'bg-[#6F42C1]/10 text-[#6F42C1] border border-[#6F42C1]/20'
                          : 'bg-emerald-100 text-emerald-800'
                      }`}
                    >
                      <ShieldCheck className="w-3 h-3" />
                      {p.escrowStatus}
                    </span>
                  </td>
                  <td className="py-4 px-6 text-right">
                    <button
                      type="button"
                      onClick={() => handleDownloadReceipt(p)}
                      className="p-2 rounded-lg bg-white border border-[#E2E8F0] hover:bg-[#6F42C1]/10 hover:border-[#6F42C1]/20 text-[#5A6B82] hover:text-[#6F42C1] transition-colors cursor-pointer inline-flex items-center gap-1 text-[11px] font-bold"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Invoice Receipt</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* DEPOSIT INTO ESCROW MODAL */}
      {isDepositModalOpen && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs z-50 flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white rounded-2xl border border-[#E2E8F0] shadow-2xl max-w-xl w-full p-6 sm:p-8 space-y-6 animate-in zoom-in-95">
            <div className="flex items-start justify-between border-b border-[#E2E8F0] pb-4">
              <div>
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#6F42C1]/10 text-[#6F42C1] uppercase border border-[#6F42C1]/20">
                  Buyer Protection
                </span>
                <h3 className="text-lg font-extrabold text-[#1E293B] mt-1">
                  Deposit Funds to Escrow Account
                </h3>
                <p className="text-xs text-[#5A6B82] font-semibold">
                  Secure funds for your active purchase order via RTGS, NEFT, or Instant B2B Gateway.
                </p>
              </div>
              <button
                type="button"
                onClick={() => setIsDepositModalOpen(false)}
                className="p-2 rounded-xl text-[#5A6B82] hover:bg-[#F4F7FC] transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleDepositSubmit} className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-[#1E293B] mb-1 uppercase">
                    Linked Purchase Order
                  </label>
                  <input
                    type="text"
                    value={depositOrderId}
                    onChange={(e) => setDepositOrderId(e.target.value)}
                    className="w-full px-3 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl text-xs font-bold text-[#1E293B] focus:outline-none focus:border-[#6F42C1]"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-[#1E293B] mb-1 uppercase">
                    Escrow Deposit Amount (₹)
                  </label>
                  <input
                    type="number"
                    value={depositAmount}
                    onChange={(e) => setDepositAmount(parseFloat(e.target.value) || 0)}
                    className="w-full px-3 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl text-xs font-bold text-[#1E293B] focus:outline-none focus:border-[#6F42C1]"
                  />
                </div>
              </div>

              {/* Bank Virtual Escrow Account Details Box */}
              <div className="bg-[#F8FAFC] p-4 rounded-xl border border-[#E2E8F0] space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold text-[#1E293B] uppercase">
                    Dedicated Virtual Escrow Account Details
                  </span>
                  <span className="text-[10px] font-bold text-[#6F42C1] bg-[#6F42C1]/10 px-2 py-0.5 rounded">
                    Auto-Reconciled
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-2 text-xs pt-1 border-t border-[#E2E8F0]">
                  <div>
                    <span className="text-[10px] text-[#5A6B82]">Bank Name:</span>
                    <p className="font-bold text-[#1E293B]">ICICI Bank Corporate Banking</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-[#5A6B82]">Beneficiary Name:</span>
                    <p className="font-bold text-[#1E293B]">PlastoShip Escrow Services LLP</p>
                  </div>
                  <div>
                    <span className="text-[10px] text-[#5A6B82]">Virtual Account No:</span>
                    <div className="flex items-center gap-1.5">
                      <p className="font-mono font-bold text-[#1E293B]">PLASTO772019</p>
                      <button
                        type="button"
                        onClick={() => copyToClipboard('PLASTO772019', 'acc')}
                        className="text-[#5A6B82] hover:text-[#1E293B]"
                      >
                        {copiedField === 'acc' ? <Check className="w-3 h-3 text-[#6F42C1]" /> : <Copy className="w-3 h-3" />}
                      </button>
                    </div>
                  </div>
                  <div>
                    <span className="text-[10px] text-[#5A6B82]">IFSC Code:</span>
                    <div className="flex items-center gap-1.5">
                      <p className="font-mono font-bold text-[#1E293B]">ICIC0000104</p>
                      <button
                        type="button"
                        onClick={() => copyToClipboard('ICIC0000104', 'ifsc')}
                        className="text-[#5A6B82] hover:text-[#1E293B]"
                      >
                        {copiedField === 'ifsc' ? <Check className="w-3 h-3 text-[#6F42C1]" /> : <Copy className="w-3 h-3" />}
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-[#E2E8F0]">
                <button
                  type="button"
                  onClick={() => setIsDepositModalOpen(false)}
                  className="px-4 py-2.5 rounded-xl bg-[#F4F7FC] text-[#1E293B] text-xs font-bold hover:bg-[#E2E8F0] transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 rounded-xl bg-[#6F42C1] hover:bg-[#5C35A5] text-white text-xs font-bold shadow-xs transition-colors cursor-pointer flex items-center gap-2"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Confirm Escrow Deposit</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
