import {
  Manufacturer,
  Distributor,
  Product,
  Category,
  Rfq,
  Order,
  SubscriptionPlan,
  SubscriptionRecord,
  PaymentTransaction,
  Invoice,
  CMSBanner,
  CMSAnnouncement,
  CMSFeaturedItem,
  ManufacturerProfileData,
  ManufacturerKycDoc,
  ManufacturerInventoryItem,
  ManufacturerQuotation,
  ManufacturerSettlement,
  DistributorProfileData,
  DistributorTransaction,
  DistributorKycDoc,
  DistributorEscrowPayment,
  DistributorDeliveryAddress,
} from './types';

export const INITIAL_MANUFACTURERS: Manufacturer[] = [
  {
    id: 'MFR-GJ-1042',
    companyName: 'Morbi Polymer Extrusions Pvt Ltd',
    contactPerson: 'Jayesh Patel',
    email: 'jayesh@morbipolymers.in',
    phone: '+91 98250 44120',
    city: 'Morbi',
    industrialZone: 'Makansar Industrial Area',
    gstin: '24AAACM4921D1ZP',
    category: 'HDPE Granules & Pipe Resins',
    categories: ['HDPE Granules', 'Pipe Resins', 'Blow Moulding'],
    kycStatus: 'Pending',
    subscription: 'Diamond',
    accountStatus: 'Pending Review',
    registeredDate: '2026-08-28',
    capacityMt: 4500,
    panNumber: 'AAACM4921D',
    cinNumber: 'U25209GJ2018PTC104521',
    productsCount: 14,
    legalEntityType: 'Private Limited Company',
    designation: 'Managing Director & Operations Head',
    altPhone: '+91 2822 249010',
    plantAddress: 'Plot No. 42-45, Survey 118/P, National Highway 8A, Makansar, Morbi, Gujarat 363642',
    registeredOfficeAddress: 'Office 302, Business Point, Sanala Road, Morbi, Gujarat 363641',
    district: 'Morbi',
    state: 'Gujarat',
    pincode: '363642',
    establishedYear: 2018,
    website: 'www.morbipolymers.in',
    powerLoadKw: 750,
    plantAreaSqFt: 35000,
    productionLines: '4 High-Speed Twin-Screw Extrusion Lines (Continuous Processing)',
    udyamRegistrationNo: 'UDYAM-GJ-20-0019482',
    factoryLicenseNo: 'DISH/MOR/2024/8912',
    gpcbConsentNo: 'GPCB/CCA-MRB-4190',
    bankName: 'HDFC Bank Ltd',
    bankAccountNo: '50200088192341',
    bankIfsc: 'HDFC0001092',
    bankBranch: 'Sanala Road Branch, Morbi',
    accountHolderName: 'Morbi Polymer Extrusions Pvt Ltd',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'REG-DOC-01', docType: 'Certificate of Incorporation (COI)', documentNumber: 'U25209GJ2018PTC104521', fileName: 'Certificate_of_Incorporation_MorbiPolymers.pdf', fileSize: '1.2 MB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-02', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AAACM4921D1ZP', fileName: 'GSTIN_Registration_Certificate_REG06.pdf', fileSize: '1.4 MB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-03', docType: 'Company PAN Card', documentNumber: 'AAACM4921D', fileName: 'Company_PAN_MorbiPolymers.pdf', fileSize: '840 KB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-04', docType: 'Factory Operating License (DISH)', documentNumber: 'DISH/MOR/2024/8912', fileName: 'Factory_License_Makansar_Plant.pdf', fileSize: '2.1 MB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-05', docType: 'GPCB Air & Water Consent (CCA)', documentNumber: 'GPCB/CCA-MRB-4190', fileName: 'GPCB_CCA_Pollution_Clearance.pdf', fileSize: '1.8 MB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-06', docType: 'Udyam / MSME Registration Certificate', documentNumber: 'UDYAM-GJ-20-0019482', fileName: 'Udyam_Registration_Certificate.pdf', fileSize: '920 KB', uploadDate: '2026-08-28', status: 'Pending Review' },
      { id: 'REG-DOC-07', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-HDFC-9912', fileName: 'Cancelled_Cheque_HDFC_MorbiPolymers.pdf', fileSize: '650 KB', uploadDate: '2026-08-28', status: 'Pending Review' },
    ],
  },
  {
    id: 'MFR-GJ-1088',
    companyName: 'Ahmedabad Masterbatch & Additives LLP',
    contactPerson: 'Suresh Shah',
    email: 'contact@ahdmasterbatch.com',
    phone: '+91 94260 88219',
    city: 'Ahmedabad',
    industrialZone: 'Vatva GIDC Phase IV',
    gstin: '24AALFA9023C1ZQ',
    category: 'Masterbatch & Additives',
    categories: ['Masterbatch & Additives', 'Color Concentrates', 'UV Stabilizers'],
    kycStatus: 'Approved',
    subscription: 'Gold',
    accountStatus: 'Active',
    registeredDate: '2026-07-14',
    capacityMt: 2800,
    panNumber: 'AALFA9023C',
    cinNumber: 'AAL-9023-GJ',
    productsCount: 22,
    legalEntityType: 'Limited Liability Partnership (LLP)',
    designation: 'Designated Partner & Commercial Head',
    altPhone: '+91 79 2583 1190',
    plantAddress: 'Plot 112/B, Phase IV, Vatva GIDC, Ahmedabad, Gujarat 382445',
    registeredOfficeAddress: 'Block C-4, Shivalik High Street, Keshavbaug, Ahmedabad, Gujarat 380015',
    district: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '382445',
    establishedYear: 2016,
    website: 'www.ahdmasterbatch.com',
    powerLoadKw: 520,
    plantAreaSqFt: 24000,
    productionLines: '3 Specialized Color Compounding & Dispersion Extruders',
    udyamRegistrationNo: 'UDYAM-GJ-01-0028114',
    factoryLicenseNo: 'DISH/AHD/2023/4410',
    gpcbConsentNo: 'GPCB/CCA-AHD-7719',
    bankName: 'ICICI Bank Ltd',
    bankAccountNo: '002405018892',
    bankIfsc: 'ICIC0000024',
    bankBranch: 'Vatva Industrial Area Branch, Ahmedabad',
    accountHolderName: 'Ahmedabad Masterbatch & Additives LLP',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'REG-DOC-11', docType: 'LLP Agreement & ROC Incorporation', documentNumber: 'AAL-9023-GJ', fileName: 'LLP_Agreement_Incorporation.pdf', fileSize: '1.6 MB', uploadDate: '2026-07-14', status: 'Verified' },
      { id: 'REG-DOC-12', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AALFA9023C1ZQ', fileName: 'GST_Certificate_AhmedabadMB.pdf', fileSize: '1.1 MB', uploadDate: '2026-07-14', status: 'Verified' },
      { id: 'REG-DOC-13', docType: 'LLP PAN Card', documentNumber: 'AALFA9023C', fileName: 'PAN_Card_AALFA9023C.pdf', fileSize: '780 KB', uploadDate: '2026-07-14', status: 'Verified' },
      { id: 'REG-DOC-14', docType: 'Factory Operating License (DISH)', documentNumber: 'DISH/AHD/2023/4410', fileName: 'DISH_Factory_License_Vatva.pdf', fileSize: '1.9 MB', uploadDate: '2026-07-14', status: 'Verified' },
    ],
  },
  {
    id: 'MFR-GJ-1104',
    companyName: 'Vapi Flexible Packaging Polymers',
    contactPerson: 'Rajiv Desai',
    email: 'rajiv.desai@vapiflexpack.com',
    phone: '+91 98791 22340',
    city: 'Vapi',
    industrialZone: 'GIDC Second Phase, Vapi',
    gstin: '24AABCV7712M1ZX',
    category: 'PP Woven Sacks & Films',
    categories: ['PP Woven Sacks', 'Packaging Films', 'BOPP Resins'],
    kycStatus: 'Approved',
    subscription: 'Diamond',
    accountStatus: 'Active',
    registeredDate: '2026-06-02',
    capacityMt: 6200,
    panNumber: 'AABCV7712M',
    cinNumber: 'U25200GJ2015PTC082341',
    productsCount: 18,
    legalEntityType: 'Private Limited Company',
    designation: 'Executive Director (Manufacturing)',
    altPhone: '+91 260 243 0081',
    plantAddress: 'Survey No. 340/2, GIDC Phase II, Near Canal Road, Vapi, Gujarat 396195',
    registeredOfficeAddress: 'Survey No. 340/2, GIDC Phase II, Vapi, Gujarat 396195',
    district: 'Valsad',
    state: 'Gujarat',
    pincode: '396195',
    establishedYear: 2015,
    website: 'www.vapiflexpack.com',
    powerLoadKw: 1100,
    plantAreaSqFt: 52000,
    productionLines: '6 Automated Circular Looms & Lamination Film Extrusion Lines',
    udyamRegistrationNo: 'UDYAM-GJ-25-0010992',
    factoryLicenseNo: 'DISH/VAP/2022/9011',
    gpcbConsentNo: 'GPCB/CCA-VAP-8821',
    bankName: 'State Bank of India',
    bankAccountNo: '33910029812',
    bankIfsc: 'SBIN0001602',
    bankBranch: 'GIDC Vapi Industrial Branch',
    accountHolderName: 'Vapi Flexible Packaging Polymers Pvt Ltd',
    cancelledChequeUploaded: true,
  },
  {
    id: 'MFR-GJ-1135',
    companyName: 'Surat Preform & Blow Plast Industries',
    contactPerson: 'Chetan Bhavsar',
    email: 'c.bhavsar@suratpreforms.in',
    phone: '+91 97245 11984',
    city: 'Surat',
    industrialZone: 'Sachin GIDC Estate',
    gstin: '24AAACS3341K1ZT',
    category: 'PET Preforms & Bottles',
    categories: ['PET Preforms', 'Bottles & Jars', 'Blow Moulding'],
    kycStatus: 'Pending',
    subscription: 'Silver',
    accountStatus: 'Pending Review',
    registeredDate: '2026-08-30',
    capacityMt: 1900,
    panNumber: 'AAACS3341K',
    cinNumber: 'U25202GJ2019PTC112344',
    productsCount: 8,
    legalEntityType: 'Private Limited Company',
    designation: 'Promoter & Plant Technical Head',
    altPhone: '+91 261 239 1045',
    plantAddress: 'Shed No. C-18/19, Road No. 4, Sachin GIDC Industrial Area, Surat, Gujarat 394230',
    registeredOfficeAddress: 'Shed C-18/19, Sachin GIDC, Surat, Gujarat 394230',
    district: 'Surat',
    state: 'Gujarat',
    pincode: '394230',
    establishedYear: 2019,
    website: 'www.suratpreforms.in',
    powerLoadKw: 380,
    plantAreaSqFt: 18500,
    productionLines: '2 Husky Preform Injection Moulding Systems',
    udyamRegistrationNo: 'UDYAM-GJ-22-0034102',
    factoryLicenseNo: 'DISH/SUR/2024/3180',
    gpcbConsentNo: 'GPCB/CCA-SUR-6612',
    bankName: 'Axis Bank Ltd',
    bankAccountNo: '921020038810291',
    bankIfsc: 'UTIB0000412',
    bankBranch: 'Sachin Industrial Area Branch, Surat',
    accountHolderName: 'Surat Preform & Blow Plast Industries Pvt Ltd',
    cancelledChequeUploaded: true,
  },
  {
    id: 'MFR-GJ-1159',
    companyName: 'Ankleshwar Chemical Polymers Ltd',
    contactPerson: 'Dharmesh Trivedi',
    email: 'info@ankleshwarpolymers.com',
    phone: '+91 99099 33411',
    city: 'Ankleshwar',
    industrialZone: 'Ankleshwar GIDC Plot 410',
    gstin: '24AAACA5589L1ZR',
    category: 'PVC Pipes & Compounds',
    categories: ['PVC Pipes & Compounds', 'CPVC Resins', 'Cable Compounds'],
    kycStatus: 'Approved',
    subscription: 'Gold',
    accountStatus: 'Active',
    registeredDate: '2026-05-19',
    capacityMt: 5100,
    panNumber: 'AAACA5589L',
    cinNumber: 'L25201GJ2012PLC071192',
    productsCount: 31,
    legalEntityType: 'Public Limited Company (Listed)',
    designation: 'General Manager (Works & Supply Chain)',
    altPhone: '+91 2646 224 890',
    plantAddress: 'Plot No. 410 & 411, GIDC Chemical Zone, Ankleshwar, Gujarat 393002',
    registeredOfficeAddress: 'Plot 410, GIDC Industrial Estate, Ankleshwar, Gujarat 393002',
    district: 'Bharuch',
    state: 'Gujarat',
    pincode: '393002',
    establishedYear: 2012,
    website: 'www.ankleshwarpolymers.com',
    powerLoadKw: 950,
    plantAreaSqFt: 48000,
    productionLines: '5 High-Output PVC/CPVC Conical Twin Screw Extrusion Lines',
    udyamRegistrationNo: 'UDYAM-GJ-06-0004910',
    factoryLicenseNo: 'DISH/ANK/2021/1190',
    gpcbConsentNo: 'GPCB/CCA-ANK-9902',
    bankName: 'Kotak Mahindra Bank',
    bankAccountNo: '8810293811',
    bankIfsc: 'KKBK0000841',
    bankBranch: 'Ankleshwar GIDC Branch',
    accountHolderName: 'Ankleshwar Chemical Polymers Ltd',
    cancelledChequeUploaded: true,
  },
  {
    id: 'MFR-GJ-1180',
    companyName: 'Rajkot Rotomoulding Tanks & Granules',
    contactPerson: 'Pravin Vaghela',
    email: 'pravin@rajkotrotomould.com',
    phone: '+91 98242 77610',
    city: 'Rajkot',
    industrialZone: 'Aji GIDC Industrial Estate',
    gstin: '24AAAPR9901B1ZU',
    category: 'Rotomoulding Powders',
    categories: ['Rotomoulding Powders', 'Water Storage Tanks', 'LLDPE Granules'],
    kycStatus: 'Rejected',
    kycReason: 'Factory license copy expired and electricity bill address mismatch with GST registration.',
    subscription: 'Starter',
    accountStatus: 'Rejected',
    registeredDate: '2026-08-11',
    capacityMt: 1200,
    panNumber: 'AAAPR9901B',
    cinNumber: 'U25204GJ2021PTC120934',
    productsCount: 4,
    legalEntityType: 'Private Limited Company',
    designation: 'Managing Director',
    altPhone: '+91 281 238 9011',
    plantAddress: 'Plot 78, Road F, Aji GIDC Phase II, Rajkot, Gujarat 360003',
    registeredOfficeAddress: 'Plot 78, Road F, Aji GIDC, Rajkot, Gujarat 360003',
    district: 'Rajkot',
    state: 'Gujarat',
    pincode: '360003',
    establishedYear: 2021,
    website: 'www.rajkotrotomould.com',
    powerLoadKw: 240,
    plantAreaSqFt: 14000,
    productionLines: '2 Bi-axial Rotomoulding Carousels & Pulverizer Unit',
    udyamRegistrationNo: 'UDYAM-GJ-20-0091104',
    factoryLicenseNo: 'DISH/RJK/2021/8014',
    gpcbConsentNo: 'GPCB/CCA-RJK-3310',
    bankName: 'Bank of Baroda',
    bankAccountNo: '0482020001948',
    bankIfsc: 'BARB0AJIGID',
    bankBranch: 'Aji GIDC Branch, Rajkot',
    accountHolderName: 'Rajkot Rotomoulding Tanks & Granules Pvt Ltd',
    cancelledChequeUploaded: false,
  },
  {
    id: 'MFR-GJ-1202',
    companyName: 'Dahej Petro Compounders Pvt Ltd',
    contactPerson: 'Karan Mehra',
    email: 'karan@dahejpetro.com',
    phone: '+91 99789 66230',
    city: 'Dahej',
    industrialZone: 'PCPIR Petrochemical Hub Dahej',
    gstin: '24AAACD1120N1ZS',
    category: 'Engineering Polymers',
    categories: ['Engineering Polymers', 'Polyamides (Nylon)', 'Polycarbonate (PC)'],
    kycStatus: 'Pending',
    subscription: 'Diamond',
    registeredDate: '2026-08-31',
    accountStatus: 'Pending Review',
    capacityMt: 8500,
    panNumber: 'AAACD1120N',
    cinNumber: 'U24100GJ2017PTC099411',
    productsCount: 12,
    legalEntityType: 'Private Limited Company',
    designation: 'Director (Operations & Polymer Sourcing)',
    altPhone: '+91 2641 289 440',
    plantAddress: 'Special Economic Zone Plot SEZ-42, PCPIR Petrochemical Hub, Dahej, Gujarat 392130',
    registeredOfficeAddress: 'Level 5, Petro Tower, Near Port Gate, Dahej, Gujarat 392130',
    district: 'Bharuch',
    state: 'Gujarat',
    pincode: '392130',
    establishedYear: 2017,
    website: 'www.dahejpetro.com',
    powerLoadKw: 1450,
    plantAreaSqFt: 68000,
    productionLines: '5 High-Torque Engineering Polymer Twin-Screw Compounding Lines',
    udyamRegistrationNo: 'UDYAM-GJ-06-0098412',
    factoryLicenseNo: 'DISH/DHJ/2024/9912',
    gpcbConsentNo: 'GPCB/CCA-DHJ-10482',
    bankName: 'HDFC Bank Ltd',
    bankAccountNo: '50200099182301',
    bankIfsc: 'HDFC0002148',
    bankBranch: 'Dahej SEZ Branch, Bharuch',
    accountHolderName: 'Dahej Petro Compounders Pvt Ltd',
    cancelledChequeUploaded: true,
  },
  {
    id: 'MFR-GJ-1165',
    companyName: 'Bharuch Petro Resins & Polymers Pvt Ltd',
    contactPerson: 'Harsh Vardhan',
    email: 'h.vardhan@bharuchpetroresins.com',
    phone: '+91 99099 88124',
    city: 'Bharuch',
    industrialZone: 'Dahej Industrial Estate Phase II',
    gstin: '24AAACB8812K1ZQ',
    category: 'Engineering Polymers',
    categories: ['Engineering Polymers', 'Polyamides (Nylon)', 'Polycarbonate (PC)'],
    kycStatus: 'Approved',
    subscription: 'Gold',
    accountStatus: 'Suspended',
    registeredDate: '2026-04-10',
    capacityMt: 3200,
    panNumber: 'AAACB8812K',
    cinNumber: 'U25209GJ2016PTC091128',
    productsCount: 6,
    legalEntityType: 'Private Limited Company',
    designation: 'Director (Operations)',
    altPhone: '+91 2642 245 810',
    plantAddress: 'Plot No. 88, Dahej Phase II, Bharuch, Gujarat 392110',
    registeredOfficeAddress: 'Plot No. 88, Dahej Phase II, Bharuch, Gujarat 392110',
    district: 'Bharuch',
    state: 'Gujarat',
    pincode: '392110',
    establishedYear: 2016,
    website: 'www.bharuchpetroresins.com',
    powerLoadKw: 650,
    plantAreaSqFt: 28000,
    productionLines: '3 Automated High-Torque Twin-Screw Compounding Extruders',
    udyamRegistrationNo: 'UDYAM-GJ-06-0033190',
    factoryLicenseNo: 'DISH/BHR/2022/6610',
    gpcbConsentNo: 'GPCB/CCA-BHR-5510',
    bankName: 'Axis Bank Ltd',
    bankAccountNo: '916020048192019',
    bankIfsc: 'UTIB0000882',
    bankBranch: 'Dahej Industrial Area Branch',
    accountHolderName: 'Bharuch Petro Resins & Polymers Pvt Ltd',
    cancelledChequeUploaded: true,
  },
];

export const INITIAL_DISTRIBUTORS: Distributor[] = [
  {
    id: 'DST-GJ-3021',
    companyName: 'Shreeji Polymer Distribution Ahmedabad',
    contactPerson: 'Mahesh Solanki',
    email: 'mahesh@shreejipolymers.in',
    phone: '+91 98251 77201',
    city: 'Ahmedabad',
    businessType: 'Wholesaler',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '2026-06-18',
    tradeVolumeYear: '₹4.8 Cr',
    gstin: '24ABFPS1092M1ZK',
    creditLimit: '₹25,00,000',
    legalEntityType: 'Partnership Firm',
    designation: 'Managing Partner',
    altPhone: '+91 79 2658 9912',
    officeAddress: 'Shop 14-16, Commercial Center, Near Odhav Ring Road, Ahmedabad, Gujarat 382415',
    warehouseAddress: 'Plot 88, Odhav Industrial Estate, Phase III, Ahmedabad, Gujarat 382415',
    district: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '382415',
    establishedYear: 2016,
    website: 'www.shreejipolymers.in',
    panNumber: 'ABFPS1092M',
    cinNumber: 'PRT/GJ/AHD/2016/8812',
    warehouseCapacitySqFt: 22000,
    monthlyProcurementMt: 350,
    targetPolymers: ['HDPE Granules', 'LLDPE Film Resins', 'PP Homopolymer'],
    bankName: 'HDFC Bank Ltd',
    bankAccountNo: '50200077182901',
    bankIfsc: 'HDFC0000412',
    bankBranch: 'Odhav Industrial Branch, Ahmedabad',
    accountHolderName: 'Shreeji Polymer Distribution',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'DST-DOC-01', docType: 'GSTIN Registration (REG-06)', documentNumber: '24ABFPS1092M1ZK', fileName: 'GSTIN_Registration_Shreeji.pdf', fileSize: '1.2 MB', uploadDate: '2026-06-18', status: 'Verified' },
      { id: 'DST-DOC-02', docType: 'Firm PAN Card Copy', documentNumber: 'ABFPS1092M', fileName: 'Firm_PAN_ABFPS1092M.pdf', fileSize: '790 KB', uploadDate: '2026-06-18', status: 'Verified' },
      { id: 'DST-DOC-03', docType: 'Registered Partnership Deed', documentNumber: 'DEED/GJ/AHD/2016', fileName: 'Partnership_Deed_Shreeji.pdf', fileSize: '2.4 MB', uploadDate: '2026-06-18', status: 'Verified' },
      { id: 'DST-DOC-04', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-HDFC-9912', fileName: 'Cancelled_Cheque_HDFC_Odhav.pdf', fileSize: '640 KB', uploadDate: '2026-06-18', status: 'Verified' },
      { id: 'DST-DOC-05', docType: 'Warehouse Lease Agreement', documentNumber: 'LEASE/ODH/88/2026', fileName: 'Odhav_Warehouse_Agreement.pdf', fileSize: '1.8 MB', uploadDate: '2026-06-18', status: 'Verified' },
    ],
  },
  {
    id: 'DST-GJ-3044',
    companyName: 'Gujarat Poly-Trade Hub Vadodara',
    contactPerson: 'Nitin Kulkarni',
    email: 'trade@polyhubvadodara.com',
    phone: '+91 94270 44190',
    city: 'Vadodara',
    businessType: 'Polymer Trader',
    kycStatus: 'Pending',
    status: 'Pending Review',
    joinedDate: '2026-08-29',
    tradeVolumeYear: '₹2.1 Cr',
    gstin: '24ABCPG8834F1ZM',
    creditLimit: '₹15,00,000',
    legalEntityType: 'Private Limited Company',
    designation: 'Director (Trading & Sourcing)',
    altPhone: '+91 265 233 1180',
    officeAddress: 'Office 402, Platinum Heights, Makarpura Main Road, Vadodara, Gujarat 390010',
    warehouseAddress: 'Shed 12, GIDC Makarpura Industrial Area, Vadodara, Gujarat 390010',
    district: 'Vadodara',
    state: 'Gujarat',
    pincode: '390010',
    establishedYear: 2020,
    website: 'www.polyhubvadodara.com',
    panNumber: 'ABCPG8834F',
    cinNumber: 'U51909GJ2020PTC118942',
    warehouseCapacitySqFt: 15000,
    monthlyProcurementMt: 180,
    targetPolymers: ['PVC Resin K-67', 'CPVC Compound', 'Masterbatch Additives'],
    bankName: 'ICICI Bank Ltd',
    bankAccountNo: '003205019921',
    bankIfsc: 'ICIC0000032',
    bankBranch: 'Makarpura Branch, Vadodara',
    accountHolderName: 'Gujarat Poly-Trade Hub Pvt Ltd',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'DST-DOC-11', docType: 'Certificate of Incorporation (COI)', documentNumber: 'U51909GJ2020PTC118942', fileName: 'COI_Polyhub_Vadodara.pdf', fileSize: '1.5 MB', uploadDate: '2026-08-29', status: 'Pending Review' },
      { id: 'DST-DOC-12', docType: 'GSTIN Registration (REG-06)', documentNumber: '24ABCPG8834F1ZM', fileName: 'GST_Certificate_Vadodara.pdf', fileSize: '1.1 MB', uploadDate: '2026-08-29', status: 'Pending Review' },
      { id: 'DST-DOC-13', docType: 'Company PAN Card Copy', documentNumber: 'ABCPG8834F', fileName: 'PAN_ABCPG8834F.pdf', fileSize: '810 KB', uploadDate: '2026-08-29', status: 'Pending Review' },
      { id: 'DST-DOC-14', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-ICICI-0032', fileName: 'Cancelled_Cheque_ICICI.pdf', fileSize: '580 KB', uploadDate: '2026-08-29', status: 'Pending Review' },
      { id: 'DST-DOC-15', docType: 'Audited Financials FY 25-26', documentNumber: 'CA-AUD-2026-90', fileName: 'Audited_Balance_Sheet.pdf', fileSize: '3.2 MB', uploadDate: '2026-08-29', status: 'Pending Review' },
    ],
  },
  {
    id: 'DST-GJ-3068',
    companyName: 'Saurashtra Plastic Raw Material Suppliers',
    contactPerson: 'Haresh Patel',
    email: 'sales@saurashtraplastics.in',
    phone: '+91 98240 55198',
    city: 'Rajkot',
    businessType: 'Industrial Supplier',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '2026-04-12',
    tradeVolumeYear: '₹6.2 Cr',
    gstin: '24AAFPS9912K1ZQ',
    creditLimit: '₹40,00,000',
    legalEntityType: 'Partnership Firm',
    designation: 'Senior Partner',
    altPhone: '+91 281 246 7790',
    officeAddress: 'Shop 22, Trade Center, Dhebar Road, Rajkot, Gujarat 360002',
    warehouseAddress: 'Survey 102/1, Metoda GIDC Gate 2, Rajkot, Gujarat 360021',
    district: 'Rajkot',
    state: 'Gujarat',
    pincode: '360021',
    establishedYear: 2014,
    website: 'www.saurashtraplastics.in',
    panNumber: 'AAFPS9912K',
    cinNumber: 'PRT/GJ/RJK/2014/901',
    warehouseCapacitySqFt: 30000,
    monthlyProcurementMt: 500,
    targetPolymers: ['PP Homopolymer', 'PP Copolymer', 'HDPE Injection Moulding', 'Rotomoulding LLDPE'],
    bankName: 'State Bank of India',
    bankAccountNo: '30910029381',
    bankIfsc: 'SBIN0003821',
    bankBranch: 'Dhebar Road Branch, Rajkot',
    accountHolderName: 'Saurashtra Plastic Raw Material Suppliers',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'DST-DOC-21', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AAFPS9912K1ZQ', fileName: 'GST_Reg_SaurashtraPlastics.pdf', fileSize: '1.3 MB', uploadDate: '2026-04-12', status: 'Verified' },
      { id: 'DST-DOC-22', docType: 'Firm PAN Card', documentNumber: 'AAFPS9912K', fileName: 'PAN_AAFPS9912K.pdf', fileSize: '850 KB', uploadDate: '2026-04-12', status: 'Verified' },
      { id: 'DST-DOC-23', docType: 'Partnership Registration Certificate', documentNumber: 'ROF/RJK/2014/19', fileName: 'Partnership_Registration.pdf', fileSize: '1.9 MB', uploadDate: '2026-04-12', status: 'Verified' },
      { id: 'DST-DOC-24', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-SBI-3091', fileName: 'SBI_Cancelled_Cheque.pdf', fileSize: '620 KB', uploadDate: '2026-04-12', status: 'Verified' },
    ],
  },
  {
    id: 'DST-GJ-3091',
    companyName: 'Surat Diamond City Resins Agency',
    contactPerson: 'Bhavesh Mehta',
    email: 'bhavesh@suratresins.com',
    phone: '+91 97250 88312',
    city: 'Surat',
    businessType: 'Retailer',
    kycStatus: 'Approved',
    status: 'Active',
    joinedDate: '2026-07-03',
    tradeVolumeYear: '₹1.7 Cr',
    gstin: '24AABCS4451R1ZJ',
    creditLimit: '₹10,00,000',
    legalEntityType: 'Sole Proprietorship',
    designation: 'Proprietor',
    altPhone: '+91 261 241 8802',
    officeAddress: 'Shop 5-6, Diamond Poly Center, Ring Road, Surat, Gujarat 395002',
    warehouseAddress: 'Plot 45, Udhna Udyog Nagar, Surat, Gujarat 394210',
    district: 'Surat',
    state: 'Gujarat',
    pincode: '394210',
    establishedYear: 2019,
    website: 'www.suratresins.com',
    panNumber: 'AABCS4451R',
    cinNumber: 'PROP/SUR/2019/3301',
    warehouseCapacitySqFt: 12000,
    monthlyProcurementMt: 120,
    targetPolymers: ['PET Resin Bottle Grade', 'LLDPE Film Grade', 'Polystyrene (GPPS)'],
    bankName: 'Axis Bank Ltd',
    bankAccountNo: '91802008819230',
    bankIfsc: 'UTIB0000109',
    bankBranch: 'Ring Road Branch, Surat',
    accountHolderName: 'Surat Diamond City Resins Agency',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'DST-DOC-31', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AABCS4451R1ZJ', fileName: 'GST_SuratResins.pdf', fileSize: '1.1 MB', uploadDate: '2026-07-03', status: 'Verified' },
      { id: 'DST-DOC-32', docType: 'Proprietor PAN Card', documentNumber: 'AABCS4451R', fileName: 'PAN_AABCS4451R.pdf', fileSize: '760 KB', uploadDate: '2026-07-03', status: 'Verified' },
      { id: 'DST-DOC-33', docType: 'Udyam Registration Certificate', documentNumber: 'UDYAM-GJ-22-0019280', fileName: 'Udyam_SuratResins.pdf', fileSize: '980 KB', uploadDate: '2026-07-03', status: 'Verified' },
      { id: 'DST-DOC-34', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-AXIS-9180', fileName: 'Axis_Cheque_Surat.pdf', fileSize: '540 KB', uploadDate: '2026-07-03', status: 'Verified' },
    ],
  },
  {
    id: 'DST-GJ-3110',
    companyName: 'Gandhinagar Green Polymers & Agro Sacks',
    contactPerson: 'Vikramsinh Vaghela',
    email: 'vikram@gnagroplastics.in',
    phone: '+91 99241 66720',
    city: 'Gandhinagar',
    businessType: 'Wholesaler',
    kycStatus: 'Pending',
    status: 'Pending Review',
    joinedDate: '2026-08-30',
    tradeVolumeYear: '₹3.4 Cr',
    gstin: '24AAGCS7710B1ZY',
    creditLimit: '₹20,00,000',
    legalEntityType: 'Limited Liability Partnership (LLP)',
    designation: 'Designated Partner',
    altPhone: '+91 79 2328 4490',
    officeAddress: 'C-201, Infocity Complex, Sector 9, Gandhinagar, Gujarat 382007',
    warehouseAddress: 'Plot 19/A, Sector 28 GIDC Industrial Estate, Gandhinagar, Gujarat 382028',
    district: 'Gandhinagar',
    state: 'Gujarat',
    pincode: '382028',
    establishedYear: 2021,
    website: 'www.gnagroplastics.in',
    panNumber: 'AAGCS7710B',
    cinNumber: 'AAY-9912-GJ',
    warehouseCapacitySqFt: 18000,
    monthlyProcurementMt: 240,
    targetPolymers: ['PP Woven Fabric Resins', 'Mulch Film Polymers', 'Drip Irrigation HDPE'],
    bankName: 'Kotak Mahindra Bank',
    bankAccountNo: '8820194812',
    bankIfsc: 'KKBK0000812',
    bankBranch: 'Sector 16 Branch, Gandhinagar',
    accountHolderName: 'Gandhinagar Green Polymers LLP',
    cancelledChequeUploaded: true,
    registrationDocs: [
      { id: 'DST-DOC-41', docType: 'LLP Agreement & ROC Incorporation', documentNumber: 'AAY-9912-GJ', fileName: 'LLP_Agreement_GNAgro.pdf', fileSize: '1.7 MB', uploadDate: '2026-08-30', status: 'Pending Review' },
      { id: 'DST-DOC-42', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AAGCS7710B1ZY', fileName: 'GST_GNAgro.pdf', fileSize: '1.2 MB', uploadDate: '2026-08-30', status: 'Pending Review' },
      { id: 'DST-DOC-43', docType: 'LLP PAN Card Copy', documentNumber: 'AAGCS7710B', fileName: 'PAN_AAGCS7710B.pdf', fileSize: '820 KB', uploadDate: '2026-08-30', status: 'Pending Review' },
      { id: 'DST-DOC-44', docType: 'Bank Cancelled Cheque Leaf', documentNumber: 'CHQ-KOTAK-8820', fileName: 'Kotak_Cheque_Leaf.pdf', fileSize: '610 KB', uploadDate: '2026-08-30', status: 'Pending Review' },
    ],
  },
  {
    id: 'DST-GJ-3133',
    companyName: 'Bhavnagar Maritime Packaging Traders',
    contactPerson: 'Ghanshyam Gohil',
    email: 'info@bhavnagarpackaging.com',
    phone: '+91 98244 11092',
    city: 'Bhavnagar',
    businessType: 'Industrial Supplier',
    kycStatus: 'Rejected',
    kycReason: 'Bank statement over 6 months old and failed direct tele-verification check.',
    status: 'Rejected',
    joinedDate: '2026-08-15',
    tradeVolumeYear: '₹95 Lakh',
    gstin: '24AABCG1209D1ZH',
    creditLimit: '₹5,00,000',
    legalEntityType: 'Sole Proprietorship',
    designation: 'Proprietor & Trader',
    altPhone: '+91 278 251 9022',
    officeAddress: 'Shop 10, Port Road Commercial Hub, Bhavnagar, Gujarat 364001',
    warehouseAddress: 'Plot 31, Chitra GIDC Industrial Estate, Bhavnagar, Gujarat 364004',
    district: 'Bhavnagar',
    state: 'Gujarat',
    pincode: '364004',
    establishedYear: 2022,
    website: 'www.bhavnagarpackaging.com',
    panNumber: 'AABCG1209D',
    cinNumber: 'PROP/BHV/2022/104',
    warehouseCapacitySqFt: 8000,
    monthlyProcurementMt: 65,
    targetPolymers: ['HM-HDPE Film Grade', 'LDPE Shrink Film', 'Stretch Film Granules'],
    bankName: 'Bank of Baroda',
    bankAccountNo: '0281020000912',
    bankIfsc: 'BARB0CHITRA',
    bankBranch: 'Chitra GIDC Branch, Bhavnagar',
    accountHolderName: 'Bhavnagar Maritime Packaging Traders',
    cancelledChequeUploaded: false,
    registrationDocs: [
      { id: 'DST-DOC-51', docType: 'GSTIN Registration (REG-06)', documentNumber: '24AABCG1209D1ZH', fileName: 'GST_Bhavnagar.pdf', fileSize: '1.0 MB', uploadDate: '2026-08-15', status: 'Rejected' },
      { id: 'DST-DOC-52', docType: 'Proprietor PAN Card', documentNumber: 'AABCG1209D', fileName: 'PAN_AABCG1209D.pdf', fileSize: '720 KB', uploadDate: '2026-08-15', status: 'Rejected' },
    ],
  },
  {
    id: 'DST-GJ-3140',
    companyName: 'Kutch Poly Logistics & Distribution LLP',
    contactPerson: 'Kishore Jadeja',
    email: 'k.jadeja@kutchpolylogistics.in',
    phone: '+91 97241 88902',
    city: 'Gandhidham',
    businessType: 'Wholesaler',
    kycStatus: 'Approved',
    status: 'Suspended',
    joinedDate: '2026-06-18',
    tradeVolumeYear: '₹2.8 Crore',
    gstin: '24AABCK4410E1ZV',
    creditLimit: '₹25,00,000',
    legalEntityType: 'Limited Liability Partnership (LLP)',
    designation: 'Managing Partner',
    altPhone: '+91 2836 231 109',
    officeAddress: 'Office 402, Port View Complex, Oslo Circle, Gandhidham, Gujarat 370201',
    warehouseAddress: 'Survey 22/P, Kandla Port Road, Gandhidham, Kutch, Gujarat 370201',
    district: 'Kutch',
    state: 'Gujarat',
    pincode: '370201',
    establishedYear: 2019,
    website: 'www.kutchpolylogistics.in',
    panNumber: 'AABCK4410E',
    cinNumber: 'AAN-4410-GJ',
    warehouseCapacitySqFt: 18000,
    monthlyProcurementMt: 140,
    targetPolymers: ['Polypropylene (PP)', 'PVC Resin S-65D', 'LLDPE Film'],
    bankName: 'State Bank of India',
    bankAccountNo: '38190028109',
    bankIfsc: 'SBIN0001090',
    bankBranch: 'Gandhidham Main Branch',
    accountHolderName: 'Kutch Poly Logistics & Distribution LLP',
    cancelledChequeUploaded: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'PRD-8821',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=300&auto=format&fit=crop&q=80',
    productName: 'HDPE Blow Moulding Granules',
    manufacturerId: 'MFR-GJ-1042',
    manufacturerName: 'Morbi Polymer Extrusions Pvt Ltd',
    category: 'HDPE Granules',
    polymerGrade: 'B56003 Virgin Polymer',
    pricePerKg: 108.5,
    minOrderQuantity: '5',
    status: 'Pending',
    stockQuantity: '120 MT',
    submittedDate: '2026-08-29',
    description: 'High-density polyethylene virgin granules engineered specifically for containers, industrial drums, and chemical bottles with superior stress crack resistance.',
    hsnCode: '39012000',
    mfi: '0.35 g/10min',
    density: '0.956 g/cm³',
  },
  {
    id: 'PRD-8834',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    productName: 'White TiO2 Masterbatch 70% Concentration',
    manufacturerId: 'MFR-GJ-1088',
    manufacturerName: 'Ahmedabad Masterbatch & Additives LLP',
    category: 'Masterbatch & Additives',
    polymerGrade: 'MB-W70 Rutile Grade',
    pricePerKg: 142.0,
    minOrderQuantity: '500 Kilograms',
    status: 'Approved',
    stockQuantity: '45 MT',
    submittedDate: '2026-08-10',
    description: 'Premium rutile titanium dioxide concentrate in LLDPE carrier resin. Offers exceptional opacity, gloss, and dispersion for multilayer film and blow moulding.',
    hsnCode: '32061110',
    mfi: '12 g/10min',
    density: '1.85 g/cm³',
  },
  {
    id: 'PRD-8849',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80',
    productName: 'PP Raffia Grade Virgin Granules',
    manufacturerId: 'MFR-GJ-1104',
    manufacturerName: 'Vapi Flexible Packaging Polymers',
    category: 'PP Woven Sacks',
    polymerGrade: 'H030SG Homopolymer',
    pricePerKg: 96.2,
    minOrderQuantity: '10',
    status: 'Approved',
    stockQuantity: '300 MT',
    submittedDate: '2026-07-25',
    description: 'Polypropylene homopolymer suitable for high-speed tape lines, woven sacks, leno bags, tarpaulins, and monofilament yarn.',
    hsnCode: '39021000',
    mfi: '3.2 g/10min',
    density: '0.905 g/cm³',
  },
  {
    id: 'PRD-8862',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=300&auto=format&fit=crop&q=80',
    productName: 'PET Bottle Grade Preforms 28mm Neck (18.5g)',
    manufacturerId: 'MFR-GJ-1135',
    manufacturerName: 'Surat Preform & Blow Plast Industries',
    category: 'PET Preforms',
    polymerGrade: 'IV 0.80 Clean Virgin PET',
    pricePerKg: 116.0,
    minOrderQuantity: '50,000 Pieces',
    status: 'Pending',
    stockQuantity: '650,000 Pcs',
    submittedDate: '2026-08-31',
    description: 'Optically clear 18.5g PET preforms with PCO 1881 neck finish for carbonated beverage, mineral water, and edible oil packaging.',
    hsnCode: '39233090',
    mfi: 'IV 0.80 dL/g',
    density: '1.34 g/cm³',
  },
  {
    id: 'PRD-8877',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=300&auto=format&fit=crop&q=80',
    productName: 'PVC Pipe Compound Rigid K-67 Grade Resin',
    manufacturerId: 'MFR-GJ-1159',
    manufacturerName: 'Ankleshwar Chemical Polymers Ltd',
    category: 'PVC Pipes & Compounds',
    polymerGrade: 'Suspension Resin K-Value 67',
    pricePerKg: 84.5,
    minOrderQuantity: '8',
    status: 'Approved',
    stockQuantity: '180 MT',
    submittedDate: '2026-08-15',
    description: 'Suspension grade PVC resin for rigid pipe extrusion, conduit manufacturing, and rainwater drainage systems with high tensile resistance.',
    hsnCode: '39041020',
    mfi: 'K-Value 67 ± 1',
    density: '1.40 g/cm³',
  },
  {
    id: 'PRD-8890',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300&auto=format&fit=crop&q=80',
    productName: 'LLDPE Rotomoulding Micro-Powder (35 Mesh)',
    manufacturerId: 'MFR-GJ-1180',
    manufacturerName: 'Rajkot Rotomoulding Tanks & Granules',
    category: 'Rotomoulding Powders',
    polymerGrade: 'LLDPE Hexene 35 Mesh',
    pricePerKg: 118.0,
    minOrderQuantity: '3',
    status: 'Rejected',
    rejectionReason: 'Missing batch testing certificate for UV-8 stabilizer and environmental stress crack resistance (ESCR).',
    stockQuantity: '20 MT',
    submittedDate: '2026-08-14',
    description: 'Hexene comonomer based linear low density polyethylene powder specifically milled for rotational moulding of overhead water tanks.',
    hsnCode: '39011010',
    mfi: '4.5 g/10min',
    density: '0.935 g/cm³',
  },
  {
    id: 'PRD-8903',
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=300&auto=format&fit=crop&q=80',
    productName: 'Engineering Polyamide Nylon-6 Granules',
    manufacturerId: 'MFR-GJ-1202',
    manufacturerName: 'Dahej Petro Compounders Pvt Ltd',
    category: 'Engineering Polymers',
    polymerGrade: 'PA6 Unfilled Virgin Grade',
    pricePerKg: 215.0,
    minOrderQuantity: '1',
    status: 'Pending',
    stockQuantity: '60 MT',
    submittedDate: '2026-08-30',
    description: 'High mechanical strength, thermal endurance, and abrasion resistance for automotive fasteners, electrical housings, and precision gears.',
    hsnCode: '39081010',
    mfi: 'Viscosity Index 145',
    density: '1.14 g/cm³',
  },
  {
    id: 'PRD-8915',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=300&auto=format&fit=crop&q=80',
    productName: 'Recycled Polycarbonate (PC) Regrind Flakes',
    manufacturerId: 'MFR-GJ-1165',
    manufacturerName: 'Bharuch Petro Resins & Polymers Pvt Ltd',
    category: 'Engineering Polymers',
    polymerGrade: 'PC Optical Regrind Clear',
    pricePerKg: 135.0,
    minOrderQuantity: '2',
    status: 'Suspended',
    stockQuantity: '15 MT',
    submittedDate: '2026-07-22',
    description: 'Post-industrial clear optical polycarbonate regrind flakes. Temporarily suspended pending plant compliance update.',
    hsnCode: '39074000',
    mfi: '10.5 g/10min',
    density: '1.20 g/cm³',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'CAT-01',
    name: 'HDPE Granules',
    slug: 'hdpe-granules',
    description: 'High-density polyethylene for blow moulding, pipe extrusion, and injection moulding.',
    hsnCode: '39012000',
    productCount: 48,
    status: 'Active',
    iconName: 'Boxes',
    avgPricePerKg: 107.5,
  },
  {
    id: 'CAT-02',
    name: 'PP Woven Sacks',
    slug: 'pp-woven-sacks',
    description: 'Polypropylene homopolymer and copolymer resins for industrial packaging bags and geotextiles.',
    hsnCode: '39021000',
    productCount: 62,
    status: 'Active',
    iconName: 'Package',
    avgPricePerKg: 95.8,
  },
  {
    id: 'CAT-03',
    name: 'Masterbatch & Additives',
    slug: 'masterbatch-additives',
    description: 'Color, white, black, UV stabilizer, slip agent, and CaCO3 filler masterbatches.',
    hsnCode: '32061110',
    productCount: 84,
    status: 'Active',
    iconName: 'Layers',
    avgPricePerKg: 145.0,
  },
  {
    id: 'CAT-04',
    name: 'PET Preforms',
    slug: 'pet-preforms',
    description: 'Virgin polyethylene terephthalate preforms and resins for bottled drinks and pharma containers.',
    hsnCode: '39233090',
    productCount: 39,
    status: 'Active',
    iconName: 'Wine',
    avgPricePerKg: 114.2,
  },
  {
    id: 'CAT-05',
    name: 'PVC Pipes & Compounds',
    slug: 'pvc-pipes-compounds',
    description: 'Rigid and flexible PVC resin compounds, dry blends, and conduit pipe master mixes.',
    hsnCode: '39041020',
    productCount: 55,
    status: 'Active',
    iconName: 'Pipette',
    avgPricePerKg: 86.0,
  },
  {
    id: 'CAT-06',
    name: 'Rotomoulding Powders',
    slug: 'rotomoulding-powders',
    description: 'Micronized LLDPE powders with UV additives for seamless overhead water storage tanks.',
    hsnCode: '39011010',
    productCount: 26,
    status: 'Active',
    iconName: 'RotateCw',
    avgPricePerKg: 119.5,
  },
  {
    id: 'CAT-07',
    name: 'Engineering Polymers',
    slug: 'engineering-polymers',
    description: 'Polyamide Nylon 6/66, Polycarbonate, POM Delrin, and PBT compounds for engineering components.',
    hsnCode: '39081010',
    productCount: 31,
    status: 'Active',
    iconName: 'Cpu',
    avgPricePerKg: 228.0,
  },
  {
    id: 'CAT-08',
    name: 'Biodegradable Polymers',
    slug: 'biodegradable-polymers',
    description: 'Certified compostable PLA, PBAT, and cornstarch compounded pellets for eco-friendly carry bags.',
    hsnCode: '39139090',
    productCount: 14,
    status: 'Active',
    iconName: 'Leaf',
    avgPricePerKg: 185.0,
  },
];

export const INITIAL_RFQS: Rfq[] = [
  {
    id: 'RFQ-GJ-9410',
    distributorId: 'DST-GJ-3021',
    distributorName: 'Shreeji Polymer Distribution Ahmedabad',
    product: 'HDPE Blow Moulding Granules',
    category: 'HDPE Granules',
    quantity: '25 Metric Tons',
    targetPrice: '₹105 / Kg',
    status: 'Quotes Received',
    createdDate: '2026-08-29',
    deliveryLocation: 'Sanand Industrial Estate, Ahmedabad',
    quotesCount: 4,
    deliveryTimeline: 'Within 7 working days from LC issue',
    paymentTerms: '30% Advance, 70% on Dispatch against E-Way Bill',
    remarks: 'Need certified Reliance or IOCL equivalent with melt index testing certificate.',
  },
  {
    id: 'RFQ-GJ-9418',
    distributorId: 'DST-GJ-3068',
    distributorName: 'Saurashtra Plastic Raw Material Suppliers',
    product: 'PP Raffia Grade Virgin Granules',
    category: 'PP Woven Sacks',
    quantity: '40 Metric Tons',
    targetPrice: '₹94.5 / Kg',
    status: 'Negotiating',
    createdDate: '2026-08-27',
    deliveryLocation: 'Metoda GIDC, Rajkot',
    quotesCount: 6,
    deliveryTimeline: 'Immediate dispatch (Ex-Morbi/Vapi)',
    paymentTerms: '100% Escrow via PlastoShip Secure Pay',
    remarks: 'Bulk requirement for Saurashtra agricultural bag manufacturing units.',
  },
  {
    id: 'RFQ-GJ-9425',
    distributorId: 'DST-GJ-3044',
    distributorName: 'Gujarat Poly-Trade Hub Vadodara',
    product: 'White TiO2 Masterbatch 70% Concentration',
    category: 'Masterbatch & Additives',
    quantity: '3 Metric Tons',
    targetPrice: '₹138 / Kg',
    status: 'Open',
    createdDate: '2026-08-31',
    deliveryLocation: 'Makarpura GIDC, Vadodara',
    quotesCount: 2,
    deliveryTimeline: '10 Days',
    paymentTerms: 'PlastoShip Escrow Guarantee',
    remarks: 'Must have food contact compliance certificate (FDA CFR 177.1520).',
  },
  {
    id: 'RFQ-GJ-9433',
    distributorId: 'DST-GJ-3091',
    distributorName: 'Surat Diamond City Resins Agency',
    product: 'PET Bottle Grade Preforms 28mm Neck (18.5g)',
    category: 'PET Preforms',
    quantity: '200,000 Pieces',
    targetPrice: '₹1.12 / Piece',
    status: 'Awarded',
    createdDate: '2026-08-24',
    deliveryLocation: 'Katargam GIDC, Surat',
    quotesCount: 5,
    deliveryTimeline: 'Dispatch in 2 batches of 100k pcs',
    paymentTerms: 'Escrow Released upon delivery confirmation',
    remarks: 'Order confirmed with Surat Preform & Blow Plast Industries.',
  },
  {
    id: 'RFQ-GJ-9442',
    distributorId: 'DST-GJ-3110',
    distributorName: 'Gandhinagar Green Polymers & Agro Sacks',
    product: 'PVC Pipe Compound Rigid K-67 Grade Resin',
    category: 'PVC Pipes & Compounds',
    quantity: '18 Metric Tons',
    targetPrice: '₹82 / Kg',
    status: 'Closed',
    createdDate: '2026-08-18',
    deliveryLocation: 'Kadi GIDC Industrial Area',
    quotesCount: 3,
    deliveryTimeline: 'Completed',
    paymentTerms: 'NEFT RTGS Bank Transfer',
    remarks: 'Fulfilled by Ankleshwar Chemical Polymers Ltd.',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'PO-2026-88291',
    distributorId: 'DST-GJ-3021',
    distributor: 'Apex Polymers & Distributors LLP',
    product: 'AeroSeal 4-Piece Airtight Modular Storage Set',
    productName: 'AeroSeal 4-Piece Airtight Modular Storage Set',
    category: 'Storage Containers',
    manufacturer: 'Nilkamal Moldings & Logistics Ltd',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub',
    quantity: '2,500 Units',
    amount: 412500,
    unitPricePerKg: 165,
    orderStatus: 'In Transit',
    paymentStatus: 'Escrow Held',
    createdDate: '28 Aug 2026',
    trackingNumber: 'LR-BHW-882910',
    estimatedDelivery: 'Tomorrow, 03:30 PM',
  },
  {
    id: 'PO-2026-88240',
    distributorId: 'DST-GJ-3021',
    distributor: 'Apex Polymers & Distributors LLP',
    product: 'ThermaLock 3-Container Insulated Lunch Box',
    productName: 'ThermaLock 3-Container Insulated Lunch Box',
    category: 'Lunch Boxes',
    manufacturer: 'Milton Housewares & Appliances',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub',
    quantity: '1,800 Units',
    amount: 864000,
    unitPricePerKg: 480,
    orderStatus: 'Dispatched',
    paymentStatus: 'Escrow Held',
    createdDate: '25 Aug 2026',
    trackingNumber: 'LR-BHW-882400',
    estimatedDelivery: '03 Sep 2026',
  },
  {
    id: 'PO-2026-88195',
    distributorId: 'DST-GJ-3021',
    distributor: 'Apex Polymers & Distributors LLP',
    product: 'DuraCrate Heavy-Duty Industrial Stacking Crate',
    productName: 'DuraCrate Heavy-Duty Industrial Stacking Crate',
    category: 'Storage Containers',
    manufacturer: 'Supreme Industries Polymer Works',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub',
    quantity: '1,200 Units',
    amount: 504000,
    unitPricePerKg: 420,
    orderStatus: 'Delivered',
    paymentStatus: 'Paid to MFR',
    createdDate: '20 Aug 2026',
    trackingNumber: 'LR-BHW-881950',
    estimatedDelivery: 'Delivered on 24 Aug',
  },
  {
    id: 'PO-2026-88090',
    distributorId: 'DST-GJ-3021',
    distributor: 'Apex Polymers & Distributors LLP',
    product: 'ChefPro 3-Tier Revolving Spice Tower',
    productName: 'ChefPro 3-Tier Revolving Spice Tower',
    category: 'Kitchenware',
    manufacturer: 'Cello World Plastics LLP',
    dispatchHub: 'Pune Central Stockyard',
    quantity: '2,000 Units',
    amount: 570000,
    unitPricePerKg: 285,
    orderStatus: 'Confirmed',
    paymentStatus: 'Escrow Held',
    createdDate: '18 Aug 2026',
    trackingNumber: 'LR-PUN-880900',
    estimatedDelivery: '05 Sep 2026',
  },
  {
    id: 'ORD-GJ-7023',
    rfqId: 'RFQ-GJ-9433',
    manufacturer: 'Surat Preform & Blow Plast Industries',
    distributor: 'Surat Diamond City Resins Agency',
    product: 'PET Bottle Grade Preforms 28mm Neck (18.5g)',
    quantity: '200,000 Pieces',
    amount: 224000,
    orderStatus: 'Processing',
    createdDate: '2026-08-28',
    dispatchHub: 'Surat Central Logistics Hub',
    paymentStatus: 'Escrow Held',
    trackingNumber: 'TRK-GJ-881290',
    estimatedDelivery: '2026-09-04',
  },
  {
    id: 'ORD-GJ-7019',
    rfqId: 'RFQ-GJ-9442',
    manufacturer: 'Ankleshwar Chemical Polymers Ltd',
    distributor: 'Gandhinagar Green Polymers & Agro Sacks',
    product: 'PVC Pipe Compound Rigid K-67 Grade Resin',
    quantity: '18 MT',
    amount: 1521000,
    orderStatus: 'Completed',
    createdDate: '2026-08-20',
    dispatchHub: 'Ankleshwar Bharuch Cargo Terminal',
    paymentStatus: 'Paid to MFR',
    trackingNumber: 'TRK-GJ-880941',
    estimatedDelivery: '2026-08-24',
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'PLAN-MFR-STARTER',
    name: 'Starter Tier (MFR)',
    tag: 'Standard Plant Listing',
    tier: 'Starter',
    targetRole: 'Manufacturer',
    monthlyPrice: 2999,
    annualPrice: 29990,
    maxListings: '5 Plant Products',
    rfqAccess: 'Standard 24hr Delayed RFQ View',
    verifiedBadge: false,
    commissionRate: '2.5% Marketplace Fee',
    prioritySupport: false,
    status: 'Active',
    activeSubscribersCount: 42,
  },
  {
    id: 'PLAN-MFR-GOLD',
    name: 'Gujarat Growth Tier (Gold)',
    tag: 'Popular for GIDC Plants',
    tier: 'Gold',
    targetRole: 'Manufacturer',
    monthlyPrice: 7999,
    annualPrice: 79990,
    maxListings: '25 Plant Products',
    rfqAccess: 'Instant Real-Time RFQ Broadcasts',
    verifiedBadge: true,
    commissionRate: '1.5% Marketplace Fee',
    prioritySupport: true,
    status: 'Active',
    activeSubscribersCount: 88,
  },
  {
    id: 'PLAN-MFR-DIAMOND',
    name: 'Gujarat Industrial Elite (Diamond)',
    tag: 'For High Volume Manufacturers',
    tier: 'Diamond',
    targetRole: 'Manufacturer',
    monthlyPrice: 16999,
    annualPrice: 169990,
    maxListings: 'Unlimited Product Catalog',
    rfqAccess: 'Priority 1-Hour Direct Match & Lead Dispatch',
    verifiedBadge: true,
    commissionRate: '0.8% Marketplace Fee',
    prioritySupport: true,
    status: 'Active',
    activeSubscribersCount: 35,
  },
  {
    id: 'PLAN-DST-STARTER',
    name: 'Wholesale Buyer Basic',
    tag: 'SME Polymer Procurement',
    tier: 'Starter',
    targetRole: 'Distributor',
    monthlyPrice: 1999,
    annualPrice: 19990,
    maxListings: '3 Active RFQ Postings',
    rfqAccess: 'Standard Plant Quotations',
    verifiedBadge: false,
    commissionRate: '1.2% Escrow Fee',
    prioritySupport: false,
    status: 'Active',
    activeSubscribersCount: 29,
  },
  {
    id: 'PLAN-DST-GOLD',
    name: 'Gujarat Trade Pro (Gold)',
    tag: 'High-Volume Distributors',
    tier: 'Gold',
    targetRole: 'Distributor',
    monthlyPrice: 5999,
    annualPrice: 59990,
    maxListings: '20 Active RFQ Postings',
    rfqAccess: 'Priority Direct Plant Counter-Bids',
    verifiedBadge: true,
    commissionRate: '0.8% Escrow Fee',
    prioritySupport: true,
    status: 'Active',
    activeSubscribersCount: 64,
  },
  {
    id: 'PLAN-DST-DIAMOND',
    name: 'Distributor Enterprise (Diamond)',
    tag: 'Statewide Depots & Trading Houses',
    tier: 'Diamond',
    targetRole: 'Distributor',
    monthlyPrice: 12999,
    annualPrice: 129990,
    maxListings: 'Unlimited Bulk RFQ & Spot Allocations',
    rfqAccess: 'VIP Instant Match & Guaranteed Dispatch',
    verifiedBadge: true,
    commissionRate: '0.4% Escrow Fee',
    prioritySupport: true,
    status: 'Active',
    activeSubscribersCount: 22,
  },
];

export const INITIAL_SUBSCRIPTION_RECORDS: SubscriptionRecord[] = [
  {
    id: 'SUB-4019',
    entityType: 'Manufacturer',
    entityName: 'Morbi Polymer Extrusions Pvt Ltd',
    planName: 'Gujarat Industrial Elite (Diamond)',
    amount: 169990,
    startDate: '2025-09-01',
    renewalDate: '2026-09-01',
    status: 'Expiring Soon',
    paymentStatus: 'Paid',
  },
  {
    id: 'SUB-4032',
    entityType: 'Manufacturer',
    entityName: 'Ahmedabad Masterbatch & Additives LLP',
    planName: 'Gujarat Growth Tier (Gold)',
    amount: 79990,
    startDate: '2026-01-15',
    renewalDate: '2027-01-15',
    status: 'Active',
    paymentStatus: 'Paid',
  },
  {
    id: 'SUB-4055',
    entityType: 'Distributor',
    entityName: 'Shreeji Polymer Distribution Ahmedabad',
    planName: 'Gujarat Growth Tier (Gold)',
    amount: 79990,
    startDate: '2026-03-10',
    renewalDate: '2027-03-10',
    status: 'Active',
    paymentStatus: 'Paid',
  },
  {
    id: 'SUB-4071',
    entityType: 'Manufacturer',
    entityName: 'Vapi Flexible Packaging Polymers',
    planName: 'Gujarat Industrial Elite (Diamond)',
    amount: 169990,
    startDate: '2026-02-01',
    renewalDate: '2027-02-01',
    status: 'Active',
    paymentStatus: 'Paid',
  },
  {
    id: 'SUB-4089',
    entityType: 'Distributor',
    entityName: 'Bhavnagar Maritime Packaging Traders',
    planName: 'Starter Tier',
    amount: 2999,
    startDate: '2026-07-01',
    renewalDate: '2026-08-01',
    status: 'Expired',
    paymentStatus: 'Failed',
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'TXN-8923',
    type: 'Order Payment',
    partyName: 'Shreeji Polymer Distribution Ahmedabad',
    partyRole: 'Distributor',
    amount: 2886000,
    method: 'Razorpay B2B',
    date: '2026-08-29 14:22',
    status: 'Success',
    invoiceNumber: 'INV-2026-0941',
    referenceId: 'ORD-GJ-7035',
  },
  {
    id: 'TXN-8929',
    type: 'Escrow Settlement',
    partyName: 'Ankleshwar Chemical Polymers Ltd',
    partyRole: 'Manufacturer',
    amount: 1521000,
    method: 'NEFT/RTGS',
    date: '2026-08-24 16:45',
    status: 'Success',
    invoiceNumber: 'INV-2026-0922',
    referenceId: 'ORD-GJ-7019',
  },
  {
    id: 'TXN-8935',
    type: 'Subscription',
    partyName: 'Dahej Petro Compounders Pvt Ltd',
    partyRole: 'Manufacturer',
    amount: 169990,
    method: 'Razorpay B2B',
    date: '2026-08-31 10:15',
    status: 'Success',
    invoiceNumber: 'INV-2026-SUB-114',
    referenceId: 'SUB-4102',
  },
  {
    id: 'TXN-8941',
    type: 'Order Payment',
    partyName: 'Saurashtra Plastic Raw Material Suppliers',
    partyRole: 'Distributor',
    amount: 568000,
    method: 'Escrow',
    date: '2026-08-30 11:30',
    status: 'Success',
    invoiceNumber: 'INV-2026-0955',
    referenceId: 'ORD-GJ-7041',
  },
  {
    id: 'TXN-8948',
    type: 'Order Payment',
    partyName: 'Gujarat Poly-Trade Hub Vadodara',
    partyRole: 'Distributor',
    amount: 1627500,
    method: 'NEFT/RTGS',
    date: '2026-08-31 17:05',
    status: 'Pending',
    invoiceNumber: 'INV-2026-0960',
    referenceId: 'ORD-GJ-7052',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  // SUBSCRIPTION INVOICES
  {
    id: 'INV-2026-SUB-101',
    type: 'Subscription',
    entityName: 'Morbi Polymer Extrusions Pvt Ltd',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1042',
    planName: 'Gujarat Industrial Elite (Diamond)',
    billingPeriod: '01 Sep 2025 - 01 Sep 2026',
    amount: 169990,
    outstandingAmount: 0,
    issuedDate: '2025-09-01',
    dueDate: '2025-09-15',
    status: 'Paid',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AAACM4921D1ZP',
    hsnSacCode: '998313',
    taxableAmount: 144059,
    taxAmount: 25931,
    items: [
      {
        description: 'Gujarat Industrial Elite (Diamond Tier) - Annual Platform License',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 144059,
        total: 144059,
      },
    ],
    notes: 'Includes unlimited polymer catalog listings, verified plant badge, priority RFQ dispatch, and direct escrow integration.',
  },
  {
    id: 'INV-2026-SUB-102',
    type: 'Subscription',
    entityName: 'Ahmedabad Masterbatch & Additives LLP',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1099',
    planName: 'Gujarat Growth Tier (Gold)',
    billingPeriod: '15 Jan 2026 - 15 Jan 2027',
    amount: 79990,
    outstandingAmount: 0,
    issuedDate: '2026-01-15',
    dueDate: '2026-01-30',
    status: 'Paid',
    paymentMethod: 'NEFT/RTGS',
    gstin: '24AAFFA8820E1ZQ',
    hsnSacCode: '998313',
    taxableAmount: 67788,
    taxAmount: 12202,
    items: [
      {
        description: 'Gujarat Growth Tier (Gold Tier) - Annual Platform Membership',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 67788,
        total: 67788,
      },
    ],
    notes: 'Includes up to 50 active SKU listings and regional buyer matching across Gujarat.',
  },
  {
    id: 'INV-2026-SUB-103',
    type: 'Subscription',
    entityName: 'Shreeji Polymer Distribution Ahmedabad',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3021',
    planName: 'Gujarat Growth Tier (Gold)',
    billingPeriod: '10 Mar 2026 - 10 Mar 2027',
    amount: 79990,
    outstandingAmount: 0,
    issuedDate: '2026-03-10',
    dueDate: '2026-03-25',
    status: 'Paid',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AAAFS9910D1ZN',
    hsnSacCode: '998313',
    taxableAmount: 67788,
    taxAmount: 12202,
    items: [
      {
        description: 'Gujarat Growth Tier (Gold Tier) - Wholesaler Annual Procurement License',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 67788,
        total: 67788,
      },
    ],
    notes: 'Access to factory gate spot rates, verified plant directory, and digital escrow accounts.',
  },
  {
    id: 'INV-2026-SUB-104',
    type: 'Subscription',
    entityName: 'Vapi Flexible Packaging Polymers',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1055',
    planName: 'Gujarat Industrial Elite (Diamond)',
    billingPeriod: '01 Feb 2026 - 01 Feb 2027',
    amount: 169990,
    outstandingAmount: 0,
    issuedDate: '2026-02-01',
    dueDate: '2026-02-15',
    status: 'Paid',
    paymentMethod: 'NEFT/RTGS',
    gstin: '24AABCV9912K1ZL',
    hsnSacCode: '998313',
    taxableAmount: 144059,
    taxAmount: 25931,
    items: [
      {
        description: 'Gujarat Industrial Elite (Diamond Tier) - Annual Platform License',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 144059,
        total: 144059,
      },
    ],
    notes: 'Dedicated enterprise account management and multi-plant consignment tracking.',
  },
  {
    id: 'INV-2026-SUB-105',
    type: 'Subscription',
    entityName: 'Bhavnagar Maritime Packaging Traders',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3105',
    planName: 'Starter Tier',
    billingPeriod: '01 Jul 2026 - 01 Aug 2026',
    amount: 2999,
    outstandingAmount: 2999,
    issuedDate: '2026-07-01',
    dueDate: '2026-07-10',
    status: 'Overdue',
    paymentMethod: 'UPI',
    gstin: '24AAGPB7710K1ZT',
    hsnSacCode: '998313',
    taxableAmount: 2542,
    taxAmount: 457,
    items: [
      {
        description: 'Starter Tier - Monthly Procurement Access Plan',
        hsnSac: '998313',
        quantity: '1 Month',
        unitPrice: 2542,
        total: 2542,
      },
    ],
    notes: 'Payment renewal attempt bounced. Immediate settlement required to prevent bidding hold.',
  },
  {
    id: 'INV-2026-SUB-106',
    type: 'Subscription',
    entityName: 'Dahej Petro Compounders Pvt Ltd',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1202',
    planName: 'Gujarat Industrial Elite (Diamond)',
    billingPeriod: '31 Aug 2026 - 31 Aug 2027',
    amount: 169990,
    outstandingAmount: 0,
    issuedDate: '2026-08-31',
    dueDate: '2026-09-14',
    status: 'Paid',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AAACD1120N1ZS',
    hsnSacCode: '998313',
    taxableAmount: 144059,
    taxAmount: 25931,
    items: [
      {
        description: 'Gujarat Industrial Elite (Diamond Tier) - Annual Platform License',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 144059,
        total: 144059,
      },
    ],
    notes: 'PCPIR Petrochemical Hub Dahej verified facility integration.',
  },
  {
    id: 'INV-2026-SUB-107',
    type: 'Subscription',
    entityName: 'Saurashtra Plastic Raw Material Suppliers',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3044',
    planName: 'Gujarat Growth Tier (Gold)',
    billingPeriod: '01 Sep 2026 - 01 Sep 2027',
    amount: 79990,
    outstandingAmount: 79990,
    issuedDate: '2026-09-01',
    dueDate: '2026-09-15',
    status: 'Pending',
    paymentMethod: 'NEFT/RTGS',
    gstin: '24AAECS4421M1ZX',
    hsnSacCode: '998313',
    taxableAmount: 67788,
    taxAmount: 12202,
    items: [
      {
        description: 'Gujarat Growth Tier (Gold Tier) - Wholesaler Annual Renewal',
        hsnSac: '998313',
        quantity: '1 Year',
        unitPrice: 67788,
        total: 67788,
      },
    ],
    notes: 'Invoice generated and dispatched. Awaiting RTGS confirmation.',
  },
  {
    id: 'INV-2026-SUB-108',
    type: 'Subscription',
    entityName: 'Rajkot Rotomoulding Tanks & Granules',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1180',
    planName: 'Starter Tier',
    billingPeriod: '15 Sep 2026 - 15 Oct 2026',
    amount: 2999,
    outstandingAmount: 2999,
    issuedDate: '2026-09-02',
    dueDate: '2026-09-16',
    status: 'Draft',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AAAPR9901B1ZU',
    hsnSacCode: '998313',
    taxableAmount: 2542,
    taxAmount: 457,
    items: [
      {
        description: 'Starter Tier - Monthly Supplier Onboarding Plan',
        hsnSac: '998313',
        quantity: '1 Month',
        unitPrice: 2542,
        total: 2542,
      },
    ],
    notes: 'Draft bill scheduled for dispatch upon compliance approval.',
  },

  // SALES INVOICES
  {
    id: 'INV-2026-0941',
    type: 'Sales',
    entityName: 'Shreeji Polymer Distribution Ahmedabad',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3021',
    orderId: 'ORD-GJ-7035',
    productDescription: 'HDPE Blow Moulding Granules (25 MT)',
    billingPeriod: 'Aug 2026',
    amount: 2886000,
    outstandingAmount: 0,
    issuedDate: '2026-08-29',
    dueDate: '2026-09-05',
    status: 'Paid',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AAAFS9910D1ZN',
    hsnSacCode: '39012000',
    taxableAmount: 2445763,
    taxAmount: 440237,
    items: [
      {
        description: 'Grade B56003 Virgin Polymer Blow Moulding Granules (Reliance Specs)',
        hsnSac: '39012000',
        quantity: '25 Metric Tons',
        unitPrice: 97830.52,
        total: 2445763,
      },
    ],
    notes: 'Delivered to Sanand Industrial Hub depot. QC certificate verified.',
  },
  {
    id: 'INV-2026-0922',
    type: 'Sales',
    entityName: 'Ankleshwar Chemical Polymers Ltd',
    entityType: 'Manufacturer',
    entityId: 'MFR-GJ-1104',
    orderId: 'ORD-GJ-7019',
    productDescription: 'PVC Rigid Compound (18 MT)',
    billingPeriod: 'Aug 2026',
    amount: 1521000,
    outstandingAmount: 0,
    issuedDate: '2026-08-24',
    dueDate: '2026-08-31',
    status: 'Paid',
    paymentMethod: 'NEFT/RTGS',
    gstin: '24AAACA5510R1ZP',
    hsnSacCode: '39042200',
    taxableAmount: 1288983,
    taxAmount: 232017,
    items: [
      {
        description: 'PVC Rigid Non-Plasticized Pipe Compound (K-67 Resin)',
        hsnSac: '39042200',
        quantity: '18 Metric Tons',
        unitPrice: 71610.16,
        total: 1288983,
      },
    ],
    notes: 'Escrow settlement completed directly to Kotak Mahindra bank account.',
  },
  {
    id: 'INV-2026-0955',
    type: 'Sales',
    entityName: 'Saurashtra Plastic Raw Material Suppliers',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3044',
    orderId: 'ORD-GJ-7041',
    productDescription: 'HDPE Granules / Extrusion Resins (5 MT)',
    billingPeriod: 'Aug 2026',
    amount: 568000,
    outstandingAmount: 0,
    issuedDate: '2026-08-30',
    dueDate: '2026-09-06',
    status: 'Paid',
    paymentMethod: 'Escrow',
    gstin: '24AAECS4421M1ZX',
    hsnSacCode: '39012000',
    taxableAmount: 481356,
    taxAmount: 86644,
    items: [
      {
        description: 'HDPE Injection Moulding Granules M26500 Grade',
        hsnSac: '39012000',
        quantity: '5 Metric Tons',
        unitPrice: 96271.2,
        total: 481356,
      },
    ],
    notes: 'Escrow release authorized upon warehouse gate-in and inspection.',
  },
  {
    id: 'INV-2026-0960',
    type: 'Sales',
    entityName: 'Gujarat Poly-Trade Hub Vadodara',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3088',
    orderId: 'ORD-GJ-7052',
    productDescription: 'LLDPE Film Grade Granules (15 MT)',
    billingPeriod: 'Aug 2026',
    amount: 1627500,
    outstandingAmount: 1627500,
    issuedDate: '2026-08-31',
    dueDate: '2026-09-07',
    status: 'Pending',
    paymentMethod: 'NEFT/RTGS',
    gstin: '24AABCG8812L1ZO',
    hsnSacCode: '39011010',
    taxableAmount: 1379237,
    taxAmount: 248263,
    items: [
      {
        description: 'LLDPE Butene Grade Film Extrusion Granules (0.918 g/cc)',
        hsnSac: '39011010',
        quantity: '15 Metric Tons',
        unitPrice: 91949.13,
        total: 1379237,
      },
    ],
    notes: 'Consignment in transit under Gujarat Roadways LR-99021. Escrow deposit processing.',
  },
  {
    id: 'INV-2026-0968',
    type: 'Sales',
    entityName: 'Bhavnagar Maritime Packaging Traders',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3105',
    orderId: 'ORD-GJ-7060',
    productDescription: 'Nylon PA-6 High Impact Compound (3.5 MT)',
    billingPeriod: 'Aug 2026',
    amount: 945000,
    outstandingAmount: 945000,
    issuedDate: '2026-08-20',
    dueDate: '2026-08-27',
    status: 'Overdue',
    paymentMethod: 'Escrow',
    gstin: '24AAGPB7710K1ZT',
    hsnSacCode: '39081000',
    taxableAmount: 800847,
    taxAmount: 144153,
    items: [
      {
        description: 'Polyamide PA-6 Glass Filled 30% Natural Granules',
        hsnSac: '39081000',
        quantity: '3.5 Metric Tons',
        unitPrice: 228813.43,
        total: 800847,
      },
    ],
    notes: 'Payment deadline lapsed. Finance team automated notice sent to buyer.',
  },
  {
    id: 'INV-2026-0972',
    type: 'Sales',
    entityName: 'Surat Polymer Traders & Compounders',
    entityType: 'Distributor',
    entityId: 'DST-GJ-3062',
    orderId: 'ORD-GJ-7071',
    productDescription: 'HDPE Pipe Resins PE-100 (10 MT)',
    billingPeriod: 'Sep 2026',
    amount: 1140000,
    outstandingAmount: 1140000,
    issuedDate: '2026-09-02',
    dueDate: '2026-09-16',
    status: 'Draft',
    paymentMethod: 'Razorpay B2B',
    gstin: '24AADCS6612N1ZW',
    hsnSacCode: '39012000',
    taxableAmount: 966102,
    taxAmount: 173898,
    items: [
      {
        description: 'PE-100 Carbon Black Pipe Extrusion Pre-Compounded Resin',
        hsnSac: '39012000',
        quantity: '10 Metric Tons',
        unitPrice: 96610.2,
        total: 966102,
      },
    ],
    notes: 'Draft commercial invoice linked to pending order dispatch schedule.',
  },
];

export const INITIAL_CMS_BANNERS: CMSBanner[] = [
  {
    id: 'BNR-01',
    title: 'Gujarat PlastExpo 2026 — Verified Manufacturer Pavilion',
    subtitle: 'Connect with over 450+ certified polymer resin producers across Morbi, Vatva, and Vapi GIDCs.',
    badge: 'Regional Spotlight',
    ctaText: 'Explore Verified Suppliers',
    ctaLink: '/manufacturers',
    active: true,
    colorScheme: 'Navy',
    targetAudience: 'All',
  },
  {
    id: 'BNR-02',
    title: 'Instant Escrow Guarantee for Bulk Resin Orders',
    subtitle: 'Zero payment default risk. Funds held securely until bill-of-lading and lab QC inspection pass.',
    badge: 'Buyer Protection',
    ctaText: 'Learn About Escrow',
    ctaLink: '/rfqs',
    active: true,
    colorScheme: 'Orange',
    targetAudience: 'Distributors',
  },
  {
    id: 'BNR-03',
    title: 'Direct Supply Scheme for GIDC Micro Compounders',
    subtitle: 'Avail subsidized freight and priority spot dispatch from Dahej and Hazira petrochemical terminals.',
    badge: 'Government Scheme',
    ctaText: 'View Eligibility',
    ctaLink: '/categories',
    active: false,
    colorScheme: 'Slate',
    targetAudience: 'Manufacturers',
  },
];

export const INITIAL_CMS_ANNOUNCEMENTS: CMSAnnouncement[] = [
  {
    id: 'ANN-01',
    title: 'GST E-Way Bill 2.0 Integration Live across Gujarat Toll Plazas',
    content: 'All dispatches originated from GIDC clusters now auto-generate digital dispatch passes directly inside PlastoShip Order Management.',
    type: 'Update',
    active: true,
    updatedAt: '2026-08-30',
  },
  {
    id: 'ANN-02',
    title: 'Mandatory BIS QCO Certification for Virgin Polyethylene Grades',
    content: 'Bureau of Indian Standards compliance verification is now enforced for all HDPE and LLDPE product listings on PlastoShip Gujarat portal.',
    type: 'Alert',
    active: true,
    updatedAt: '2026-08-25',
  },
  {
    id: 'ANN-03',
    title: 'Monsoon Bulk Freight Advisory for Saurashtra & South Gujarat Ports',
    content: 'Port terminals at Pipavav, Kandla, and Hazira reporting 24hr container clearance windows. Plan your dispatch dates accordingly.',
    type: 'Notice',
    active: true,
    updatedAt: '2026-08-20',
  },
];

export const INITIAL_CMS_FEATURED: CMSFeaturedItem[] = [
  {
    id: 'FEAT-01',
    type: 'Manufacturer',
    name: 'Morbi Polymer Extrusions Pvt Ltd',
    category: 'HDPE Granules & Pipe Resins',
    locationOrPrice: 'Morbi, Gujarat',
    isFeatured: true,
    badge: 'Top Rated Manufacturer',
  },
  {
    id: 'FEAT-02',
    type: 'Manufacturer',
    name: 'Vapi Flexible Packaging Polymers',
    category: 'PP Woven Sacks & Films',
    locationOrPrice: 'Vapi, Gujarat',
    isFeatured: true,
    badge: 'Highest Capacity Plant',
  },
  {
    id: 'FEAT-03',
    type: 'Product',
    name: 'White TiO2 Masterbatch 70% Concentration',
    category: 'Masterbatch & Additives',
    locationOrPrice: '₹142 / Kg',
    isFeatured: true,
    badge: 'Best Seller',
  },
  {
    id: 'FEAT-04',
    type: 'Product',
    name: 'PP Raffia Grade Virgin Granules (H030SG)',
    category: 'PP Woven Sacks',
    locationOrPrice: '₹96.2 / Kg',
    isFeatured: true,
    badge: 'High Demand',
  },
];

export const INITIAL_RECENT_ACTIVITIES = [
  {
    id: 'ACT-01',
    title: 'New manufacturer registered',
    description: 'Dahej Petro Compounders Pvt Ltd submitted registration with 8,500 MT capacity.',
    time: '12 minutes ago',
    type: 'manufacturer',
    navScreen: 'manufacturers' as const,
  },
  {
    id: 'ACT-02',
    title: 'Product submitted for review',
    description: 'HDPE Blow Moulding Granules (Grade B56003) submitted by Morbi Polymer Extrusions.',
    time: '45 minutes ago',
    type: 'product',
    navScreen: 'products' as const,
  },
  {
    id: 'ACT-03',
    title: 'New distributor joined',
    description: 'Gandhinagar Green Polymers & Agro Sacks completed profile onboarding.',
    time: '2 hours ago',
    type: 'distributor',
    navScreen: 'distributors' as const,
  },
  {
    id: 'ACT-04',
    title: 'RFQ created',
    description: 'Shreeji Polymer created RFQ-GJ-9410 for 25 MT HDPE Granules.',
    time: '3 hours ago',
    type: 'rfq',
    navScreen: 'rfqs' as const,
  },
  {
    id: 'ACT-05',
    title: 'Subscription renewed',
    description: 'Ahmedabad Masterbatch renewed Gujarat Growth Tier (Gold) annual plan for ₹79,990.',
    time: '5 hours ago',
    type: 'subscription',
    navScreen: 'subscriptions' as const,
  },
];

export const INITIAL_MFR_PROFILE: ManufacturerProfileData = {
  id: 'MFR-GJ-1042',
  companyName: 'Morbi Polymer Extrusions Pvt Ltd',
  contactPerson: 'Jayesh Patel',
  designation: 'Managing Director & Operations Head',
  email: 'jayesh@morbipolymers.in',
  phone: '+91 98250 44120',
  altPhone: '+91 2822 249010',
  city: 'Morbi',
  state: 'Gujarat',
  pincode: '363642',
  industrialZone: 'Makansar Industrial Area',
  plantAddress: 'Plot No. 42-45, Survey 118/P, National Highway 8A, Makansar, Morbi, Gujarat 363642',
  gstin: '24AAACM4921D1ZP',
  panNumber: 'AAACM4921D',
  cinNumber: 'U25209GJ2018PTC104521',
  establishedYear: 2018,
  capacityMt: 4500,
  powerLoadKw: 750,
  plantAreaSqFt: 35000,
  primaryCategory: 'HDPE Granules & Pipe Resins',
  subscriptionTier: 'Diamond',
  subscriptionExpiry: '2026-09-28',
  kycStatus: 'Approved',
  accountStatus: 'Active',
  bankName: 'HDFC Bank Ltd',
  bankAccountNo: '50200088192341',
  bankIfsc: 'HDFC0001092',
  bankBranch: 'Sanala Road Branch, Morbi',
  accountHolderName: 'Morbi Polymer Extrusions Pvt Ltd',
  cancelledChequeUploaded: true,
  completionScore: 92,
};

export const INITIAL_MFR_KYC_DOCS: ManufacturerKycDoc[] = [
  {
    id: 'KYC-DOC-01',
    documentType: 'GSTIN Certificate (REG-06)',
    documentNumber: '24AAACM4921D1ZP',
    description: 'Government of India Goods & Services Tax Registration Certificate.',
    status: 'Verified',
    uploadDate: '2026-06-10',
    fileName: 'GST_Registration_MorbiPolymers.pdf',
    fileSize: '1.4 MB',
  },
  {
    id: 'KYC-DOC-02',
    documentType: 'Factory Operating License (GIDC / Dish)',
    documentNumber: 'MOR/FAC/2024/8912',
    description: 'Directorate of Industrial Safety & Health (DISH) Factory License.',
    status: 'Verified',
    uploadDate: '2026-06-12',
    expiryDate: '2027-12-31',
    fileName: 'Factory_License_Makansar.pdf',
    fileSize: '2.1 MB',
  },
  {
    id: 'KYC-DOC-03',
    documentType: 'Company PAN Card',
    documentNumber: 'AAACM4921D',
    description: 'Income Tax Department Permanent Account Number.',
    status: 'Verified',
    uploadDate: '2026-06-10',
    fileName: 'Company_PAN_MorbiPolymers.pdf',
    fileSize: '840 KB',
  },
  {
    id: 'KYC-DOC-04',
    documentType: 'GPCB Air & Water Consent (CCA)',
    documentNumber: 'GPCB/CCA-MRB-4190',
    description: 'Gujarat Pollution Control Board Consolidated Consent & Authorization.',
    status: 'Verified',
    uploadDate: '2026-07-02',
    expiryDate: '2028-03-31',
    fileName: 'GPCB_Pollution_Clearance.pdf',
    fileSize: '3.2 MB',
  },
  {
    id: 'KYC-DOC-05',
    documentType: 'Cancelled Cheque for Escrow Payouts',
    documentNumber: 'CHQ-HDFC-9921',
    description: 'Original bank cancelled cheque showing Account Name and IFSC code.',
    status: 'Verified',
    uploadDate: '2026-06-11',
    fileName: 'Cancelled_Cheque_HDFC.pdf',
    fileSize: '650 KB',
  },
  {
    id: 'KYC-DOC-06',
    documentType: 'BIS QCO Virgin Polymer Certificate',
    documentNumber: 'BIS/CM/L-7719203',
    description: 'Bureau of Indian Standards Quality Control Order Certification for HDPE.',
    status: 'In Review',
    uploadDate: '2026-08-25',
    expiryDate: '2027-08-24',
    fileName: 'BIS_HDPE_Testing_Cert.pdf',
    fileSize: '1.8 MB',
  },
];

export const INITIAL_MFR_INVENTORY: ManufacturerInventoryItem[] = [
  {
    id: 'INV-BCH-4011',
    productName: 'HDPE Blow Moulding Granules',
    polymerGrade: 'B56003 Virgin Polymer',
    category: 'HDPE Granules',
    batchNumber: 'MB-B56-2608A',
    warehouseLocation: 'Silo A-01 (Makansar Plant)',
    currentStockMt: 75.0,
    reorderLevelMt: 20.0,
    unitPricePerKg: 108.5,
    lastUpdated: '2026-08-30',
    status: 'In Stock',
  },
  {
    id: 'INV-BCH-4019',
    productName: 'HDPE Pipe Extrusion Resins (PE-100)',
    polymerGrade: 'PE-100 Black Carbon Loaded',
    category: 'HDPE Granules',
    batchNumber: 'MB-PE100-2608B',
    warehouseLocation: 'Silo A-03 (Makansar Plant)',
    currentStockMt: 45.0,
    reorderLevelMt: 15.0,
    unitPricePerKg: 114.0,
    lastUpdated: '2026-08-29',
    status: 'In Stock',
  },
  {
    id: 'INV-BCH-4024',
    productName: 'HDPE Injection Grade Virgin Resin',
    polymerGrade: 'M26500 High Flow MFI 7.0',
    category: 'HDPE Granules',
    batchNumber: 'MB-INJ-2607C',
    warehouseLocation: 'Bay 2 Racks (Warehouse B)',
    currentStockMt: 8.5,
    reorderLevelMt: 12.0,
    unitPricePerKg: 106.0,
    lastUpdated: '2026-08-31',
    status: 'Low Stock',
  },
  {
    id: 'INV-BCH-4032',
    productName: 'HDPE Monofilament Grade Granules',
    polymerGrade: 'M50100 Heavy Duty',
    category: 'HDPE Granules',
    batchNumber: 'MB-MONO-2608A',
    warehouseLocation: 'Bay 3 Racks (Warehouse B)',
    currentStockMt: 32.0,
    reorderLevelMt: 10.0,
    unitPricePerKg: 111.0,
    lastUpdated: '2026-08-28',
    status: 'In Stock',
  },
  {
    id: 'INV-BCH-4048',
    productName: 'LLDPE Rotomoulding Powder 35 Mesh',
    polymerGrade: 'Hexene Grade UV Stabilized',
    category: 'Rotomoulding Powders',
    batchNumber: 'MB-ROTO-2607A',
    warehouseLocation: 'Finished Goods Bay 4',
    currentStockMt: 3.0,
    reorderLevelMt: 10.0,
    unitPricePerKg: 120.0,
    lastUpdated: '2026-08-27',
    status: 'Low Stock',
  },
];

export const INITIAL_MFR_QUOTATIONS: ManufacturerQuotation[] = [
  {
    id: 'QT-9042',
    rfqId: 'RFQ-GJ-9410',
    rfqProduct: 'HDPE Blow Moulding Granules',
    distributorName: 'Shreeji Polymer Distribution Ahmedabad',
    distributorCity: 'Ahmedabad (Sanand Hub)',
    quantityRequested: '25 Metric Tons',
    quotedPricePerKg: 106.5,
    totalQuoteAmount: 2662500,
    freightTerms: 'FOR Destination',
    paymentTerms: 'PlastoShip Escrow (30/70)',
    deliveryLeadDays: 5,
    validUntil: '2026-09-08',
    status: 'Submitted',
    notes: 'Grade B56003 Virgin Polymer available for immediate batch dispatch with Reliance batch test certificate.',
    submittedAt: '2026-08-30',
  },
  {
    id: 'QT-9038',
    rfqId: 'RFQ-GJ-9418',
    rfqProduct: 'PP Raffia Grade Virgin Granules',
    distributorName: 'Saurashtra Plastic Raw Material Suppliers',
    distributorCity: 'Rajkot (Metoda GIDC)',
    quantityRequested: '40 Metric Tons',
    quotedPricePerKg: 95.0,
    totalQuoteAmount: 3800000,
    freightTerms: 'Ex-Factory',
    paymentTerms: '100% Escrow via PlastoShip',
    deliveryLeadDays: 4,
    validUntil: '2026-09-05',
    status: 'Under Review',
    notes: 'Dispatches available in 50kg HDPE woven sacks from Morbi plant.',
    submittedAt: '2026-08-28',
  },
  {
    id: 'QT-9014',
    rfqId: 'RFQ-GJ-9382',
    rfqProduct: 'HDPE Pipe Extrusion Resin (PE-100)',
    distributorName: 'Gujarat Poly-Trade Hub Vadodara',
    distributorCity: 'Vadodara',
    quantityRequested: '20 Metric Tons',
    quotedPricePerKg: 112.5,
    totalQuoteAmount: 2250000,
    freightTerms: 'FOR Destination',
    paymentTerms: '100% Escrow Released on LR',
    deliveryLeadDays: 6,
    validUntil: '2026-08-26',
    status: 'Accepted',
    notes: 'Quote accepted by buyer. Converted to Order ORD-GJ-7028.',
    submittedAt: '2026-08-20',
  },
];

export const INITIAL_MFR_SETTLEMENTS: ManufacturerSettlement[] = [
  {
    id: 'STL-2026-883',
    orderId: 'ORD-GJ-7012',
    distributorName: 'Shreeji Polymer Distribution Ahmedabad',
    orderProduct: 'HDPE Blow Moulding Granules (20 MT)',
    grossAmount: 2170000,
    platformFee: 16275, // 0.75% Diamond plan
    gstTdsDeduction: 2170, // 0.1% TDS
    netSettledAmount: 2151555,
    settlementDate: '2026-08-26',
    utrReference: 'UTR-HDFC-99120482',
    status: 'Settled to Bank',
    bankAccountLast4: '2341',
  },
  {
    id: 'STL-2026-879',
    orderId: 'ORD-GJ-6998',
    distributorName: 'Surat Diamond City Resins Agency',
    orderProduct: 'HDPE Pipe Extrusion Resins (15 MT)',
    grossAmount: 1710000,
    platformFee: 12825,
    gstTdsDeduction: 1710,
    netSettledAmount: 1695465,
    settlementDate: '2026-08-19',
    utrReference: 'UTR-HDFC-98841091',
    status: 'Settled to Bank',
    bankAccountLast4: '2341',
  },
  {
    id: 'STL-2026-890',
    orderId: 'ORD-GJ-7028',
    distributorName: 'Gujarat Poly-Trade Hub Vadodara',
    orderProduct: 'HDPE Pipe Extrusion Resin PE-100 (20 MT)',
    grossAmount: 2250000,
    platformFee: 16875,
    gstTdsDeduction: 2250,
    netSettledAmount: 2230875,
    settlementDate: '2026-09-02 (Est)',
    utrReference: 'PENDING-DISPATCH-CLEARANCE',
    status: 'Escrow Held',
    bankAccountLast4: '2341',
  },
];

export const INITIAL_MFR_ACTIVITIES = [
  {
    id: 'MFR-ACT-01',
    title: 'New RFQ Received in your Category',
    description: 'Shreeji Polymer created RFQ-GJ-9410 for 25 MT HDPE Blow Moulding Granules.',
    time: '3 hours ago',
    type: 'rfq',
    screen: 'mfr_rfqs' as const,
  },
  {
    id: 'MFR-ACT-02',
    title: 'Order Confirmed by Buyer',
    description: 'ORD-GJ-7028 confirmed for ₹22.5 Lakhs by Gujarat Poly-Trade Hub.',
    time: '6 hours ago',
    type: 'order',
    screen: 'mfr_orders' as const,
  },
  {
    id: 'MFR-ACT-03',
    title: 'Escrow Settlement Credited',
    description: '₹21,51,555 credited to HDFC Bank (A/C ...2341) for Order ORD-GJ-7012.',
    time: '1 day ago',
    type: 'payment',
    screen: 'mfr_payments' as const,
  },
  {
    id: 'MFR-ACT-04',
    title: 'Low Stock Alert Triggered',
    description: 'HDPE Injection Grade Resin dropped below 12 MT reorder threshold.',
    time: '2 days ago',
    type: 'inventory',
    screen: 'mfr_inventory' as const,
  },
  {
    id: 'MFR-ACT-05',
    title: 'Diamond Plan Renews in 22 Days',
    description: 'Your annual Diamond Tier subscription renews on 28 Sep 2026.',
    time: '3 days ago',
    type: 'subscription',
    screen: 'mfr_subscriptions' as const,
  },
];

export const INITIAL_DISTRIBUTOR_PROFILE: DistributorProfileData = {
  id: 'DST-94821 - IND',
  companyName: 'Apex Polymers & Distributors LLP',
  legalName: 'Apex Polymers & Distributors LLP',
  contactPerson: 'Rajesh Singhania',
  primaryContactPerson: 'Rajesh Singhania',
  designation: 'Authorized Sourcing Officer',
  email: 'sourcing@apexpolymers.com',
  phone: '+91 98201 45890',
  altPhone: '+91 22 2781 9901',
  city: 'Bhiwandi, Thane',
  state: 'Maharashtra',
  pincode: '421302',
  industrialZone: 'Logistics Park Road',
  officeAddress: 'Plot 42-A, Logistics Park Road, Bhiwandi, Thane, Maharashtra - 421302',
  gstin: '27AABCA5423E1Z4',
  panNumber: 'AABCA5423E',
  pan: 'AABCA5423E',
  businessType: 'Wholesaler',
  tradeVolumeYear: '₹4.85 Crore',
  annualSourcingVolume: '₹4.85 Crore',
  annualTurnover: '₹4.85 Crore',
  establishedYear: 2018,
  subscriptionTier: 'PLATINUM PRO',
  totalOrdersPlaced: 28,
  categoriesOfInterest: [
    'Storage Containers',
    'Lunch Boxes',
    'Kitchenware',
    'Cleaning Products',
    'Industrial Crates',
    'HDPE/PP Raw Resins',
  ],
  creditLimit: '₹50,00,000',
  availableCredit: '₹34,20,000',
  lockedEscrow: '₹15,80,000',
  tier: 'Platinum Distributor',
  verifiedLevel: 'Yes (Level 3)',
  kycStatus: 'Approved',
  accountStatus: 'Active',
  defaultDeliveryHub: 'Bhiwandi Central Fulfillment Hub (MH-04)',
  deliveryHubDetails: 'Dock Bay 4 & 5, Heavy Vehicle Entry 24/7 Access, Forklift Offloading Certified.',
  bankName: 'HDFC Corporate Bank',
  bankAccountNo: '50200039218941',
  bankIfsc: 'HDFC0000492',
  bankBranch: 'Bhiwandi Corporate Hub Branch',
  accountHolderName: 'Apex Polymers & Distributors LLP',
  completionScore: 100,
};

export const INITIAL_DISTRIBUTOR_KYC_DOCS: DistributorKycDoc[] = [
  {
    id: 'DST-DOC-01',
    documentType: 'GST Registration Certificate (REG-06)',
    documentNumber: '27AABCA5423E1Z4',
    description: 'Central Board of Indirect Taxes & Customs GST Registration Certificate.',
    status: 'Verified',
    uploadDate: '2026-05-10',
    expiryDate: 'Perpetual',
    fileName: 'GST_Apex_Polymers_REG06.pdf',
    fileSize: '1.4 MB',
  },
  {
    id: 'DST-DOC-02',
    documentType: 'Company PAN Card Verification',
    documentNumber: 'AABCA5423E',
    description: 'Permanent Account Number verified via Income Tax Dept NSDL Database.',
    status: 'Verified',
    uploadDate: '2026-05-10',
    expiryDate: 'Lifetime',
    fileName: 'PAN_Apex_Polymers_LLP.pdf',
    fileSize: '820 KB',
  },
  {
    id: 'DST-DOC-03',
    documentType: 'PlastoShip B2B Master Escrow & Sourcing MOU',
    documentNumber: 'MOU-PL-2026-981',
    description: 'Bi-lateral Master Escrow Service Agreement and Safe Settlement terms signed.',
    status: 'Verified',
    uploadDate: '2026-05-12',
    expiryDate: 'Renewed 2026',
    fileName: 'PlastoShip_B2B_MOU_Signed.pdf',
    fileSize: '3.1 MB',
  },
  {
    id: 'DST-DOC-04',
    documentType: 'Bank E-Mandate (NACH / Auto-Settlement)',
    documentNumber: 'EM-HDFC-99120',
    description: 'Approved auto-debit and escrow refund mandate with HDFC Corporate Bhiwandi.',
    status: 'Verified',
    uploadDate: '2026-05-15',
    expiryDate: 'Active',
    fileName: 'HDFC_NACH_Mandate_Apex.pdf',
    fileSize: '640 KB',
  },
];

export const INITIAL_DISTRIBUTOR_RFQS: Rfq[] = [
  {
    id: 'RFQ-2026-0491',
    distributorId: 'DST-94821-IND',
    distributorName: 'Apex Polymers & Distributors LLP',
    product: 'Bulk Sourcing: 50L Heavy Duty Virgin HDPE Storage Tubs',
    productName: 'Bulk Sourcing: 50L Heavy Duty Virgin HDPE Storage Tubs',
    category: 'Storage Containers',
    quantity: '3,000 Units',
    targetPrice: '₹380 / unit',
    targetPricePerKg: 380,
    status: 'Quotes Received',
    createdDate: 'Yesterday, 04:30 PM',
    deliveryLocation: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    deliveryTimeline: 'Within 10 Days',
    quotesCount: 4,
    remarks: 'Heavy gauge, food-contact grade, drop impact tested from 2 meters, customized embossed distributor logo.',
    paymentTerms: '100% Escrow Vault Guarantee',
    notes: 'Packaging: Palletized & Shrink Wrapped',
    quotes: [
      {
        id: 'QT-2026-0091-A',
        manufacturerId: 'MFR-SUPREME',
        manufacturerName: 'Supreme Industries Polymer Works',
        offeredPricePerKg: 372,
        totalOfferAmount: 1116000,
        deliveryTimelineDays: '6 Days Lead Time',
        validityDate: '08 Sep 2026',
        status: 'Pending',
        remarks: 'Includes customized distributor embossing on mold. First batch dispatch in 5 days. Freight included.',
      },
      {
        id: 'QT-2026-0091-B',
        manufacturerId: 'MFR-NILKAMAL',
        manufacturerName: 'Nilkamal Moldings & Logistics Ltd',
        offeredPricePerKg: 368,
        totalOfferAmount: 1104000,
        deliveryTimelineDays: '7 Days Lead Time',
        validityDate: '07 Sep 2026',
        status: 'Pending',
        remarks: 'Ex-Vapi factory stock ready. Extra 1.5% prompt settlement cash discount applicable. Freight included.',
      },
    ],
  },
  {
    id: 'RFQ-2026-0488',
    distributorId: 'DST-94821-IND',
    distributorName: 'Apex Polymers & Distributors LLP',
    product: 'Custom Dual-Compartment Bento Lunch Boxes (BPA Free)',
    productName: 'Custom Dual-Compartment Bento Lunch Boxes (BPA Free)',
    category: 'Lunch Boxes',
    quantity: '2,000 Units',
    targetPrice: '₹260 / unit',
    targetPricePerKg: 260,
    status: 'Quotes Received',
    createdDate: '3 days ago',
    deliveryLocation: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    deliveryTimeline: 'Within 7 Days',
    quotesCount: 3,
    remarks: 'Microwaveable, silicone seal, 2-tier with cutlery pod, export finish.',
    paymentTerms: '45-day Revolving Credit Line',
    notes: 'Packaging: Master Carton (24 pcs/carton)',
    quotes: [
      {
        id: 'QT-2026-0088-A',
        manufacturerId: 'MFR-CELLO',
        manufacturerName: 'Cello World Plastics LLP',
        offeredPricePerKg: 255,
        totalOfferAmount: 510000,
        deliveryTimelineDays: '4 Days Lead Time',
        validityDate: '06 Sep 2026',
        status: 'Pending',
        remarks: 'BPA-free certified test certificates with food migration compliance. Direct factory dispatch from Daman.',
      },
    ],
  },
  {
    id: 'RFQ-2026-0475',
    distributorId: 'DST-94821-IND',
    distributorName: 'Apex Polymers & Distributors LLP',
    product: 'Commercial 360 Spin Mop Bucket Sets with Wheels',
    productName: 'Commercial 360 Spin Mop Bucket Sets with Wheels',
    category: 'Cleaning Products',
    quantity: '1,500 Units',
    targetPrice: '₹590 / unit',
    targetPricePerKg: 590,
    status: 'Open',
    createdDate: '5 days ago',
    deliveryLocation: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    deliveryTimeline: 'Immediate Dispatch',
    quotesCount: 5,
    remarks: 'Stainless steel dry bucket basket, extra heavy rod, double microfiber refill.',
    paymentTerms: 'PlastoShip SafeEscrow',
    notes: 'Packaging: Individual Color Box',
    quotes: [
      {
        id: 'QT-2026-0075-A',
        manufacturerId: 'MFR-GALA',
        manufacturerName: 'Gala Brush & Household Corp',
        offeredPricePerKg: 575,
        totalOfferAmount: 862500,
        deliveryTimelineDays: '5 Days Lead Time',
        validityDate: '04 Sep 2026',
        status: 'Pending',
        remarks: 'Double microfiber refill and spare spinner included per unit. Handover at Ambernath plant.',
      },
    ],
  },
];

export const INITIAL_DISTRIBUTOR_QUOTATIONS: ManufacturerQuotation[] = [
  {
    id: 'QT-2026-0091-A',
    rfqId: 'RFQ-2026-0491',
    rfqProduct: 'Bulk Sourcing: 50L Heavy Duty Virgin HDPE Storage Tubs',
    distributorName: 'Apex Polymers & Distributors LLP',
    manufacturerName: 'Supreme Industries Polymer Works',
    manufacturerId: 'MFR-SUPREME',
    factoryHub: 'Jalgaon, Maharashtra',
    rating: 4.9,
    leadTime: '6 Days Lead Time',
    deliveryLeadTimeDays: 6,
    freightIncluded: true,
    escrowProtected: true,
    productName: '50L Heavy Duty Virgin HDPE Crate/Tub',
    category: 'Storage Containers',
    quantity: '3,000 Units',
    quotedPricePerKg: 372,
    quotedUnitPrice: 372,
    totalQuotationAmount: 1116000,
    totalOrderValue: 1116000,
    validUntil: '08 Sep 2026',
    status: 'Submitted',
    notes: 'Includes customized distributor embossing on mold. First batch dispatch in 5 days.',
    remarks: 'Freight Included • PlastoShip Escrow Protected • Rating: 4.9 ★ • Supreme Industries Polymer Works (Jalgaon, MH)',
    submittedAt: 'Today at 10:15 AM',
  },
  {
    id: 'QT-2026-0091-B',
    rfqId: 'RFQ-2026-0491',
    rfqProduct: 'Bulk Sourcing: 50L Heavy Duty Virgin HDPE Storage Tubs',
    distributorName: 'Apex Polymers & Distributors LLP',
    manufacturerName: 'Nilkamal Moldings & Logistics Ltd',
    manufacturerId: 'MFR-NILKAMAL',
    factoryHub: 'Vapi, Gujarat',
    rating: 4.8,
    leadTime: '7 Days Lead Time',
    deliveryLeadTimeDays: 7,
    freightIncluded: true,
    escrowProtected: true,
    productName: 'MaxiStore 50L Industrial Virgin Tub',
    category: 'Storage Containers',
    quantity: '3,000 Units',
    quotedPricePerKg: 368,
    quotedUnitPrice: 368,
    totalQuotationAmount: 1104000,
    totalOrderValue: 1104000,
    validUntil: '07 Sep 2026',
    status: 'Submitted',
    notes: 'Ex-Vapi factory stock ready. Extra 1.5% prompt settlement cash discount applicable.',
    remarks: 'Freight Included • PlastoShip Escrow Protected • Rating: 4.8 ★ • Nilkamal Moldings & Logistics Ltd (Vapi, Gujarat)',
    submittedAt: 'Today at 09:30 AM',
  },
  {
    id: 'QT-2026-0088-A',
    rfqId: 'RFQ-2026-0488',
    rfqProduct: 'Custom Dual-Compartment Bento Lunch Boxes (BPA Free)',
    distributorName: 'Apex Polymers & Distributors LLP',
    manufacturerName: 'Cello World Plastics LLP',
    manufacturerId: 'MFR-CELLO',
    factoryHub: 'Daman, UT',
    rating: 4.9,
    leadTime: '4 Days Lead Time',
    deliveryLeadTimeDays: 4,
    freightIncluded: true,
    escrowProtected: true,
    productName: 'BentoDuo 850ml Microwave Lunch Set',
    category: 'Lunch Boxes',
    quantity: '2,000 Units',
    quotedPricePerKg: 254,
    quotedUnitPrice: 254,
    totalQuotationAmount: 508000,
    totalOrderValue: 508000,
    validUntil: '06 Sep 2026',
    status: 'Submitted',
    notes: 'Silicone seal certified BPA free. Ready for dispatch with custom shrink branding.',
    remarks: 'Freight Included • PlastoShip Escrow Protected • Rating: 4.9 ★ • Cello World Plastics LLP (Daman, UT)',
    submittedAt: 'Yesterday at 02:45 PM',
  },
  {
    id: 'QT-2026-0075-A',
    rfqId: 'RFQ-2026-0475',
    rfqProduct: 'Commercial 360 Spin Mop Bucket Sets with Wheels',
    distributorName: 'Apex Polymers & Distributors LLP',
    manufacturerName: 'Gala Brush & Household Corp',
    manufacturerId: 'MFR-GALA',
    factoryHub: 'Ambernath, Maharashtra',
    rating: 4.7,
    leadTime: '5 Days Lead Time',
    deliveryLeadTimeDays: 5,
    freightIncluded: true,
    escrowProtected: true,
    productName: 'ProSpin 360 Heavy Duty Mop System',
    category: 'Cleaning Products',
    quantity: '1,500 Units',
    quotedPricePerKg: 575,
    quotedUnitPrice: 575,
    totalQuotationAmount: 862500,
    totalOrderValue: 862500,
    validUntil: '04 Sep 2026',
    status: 'Submitted',
    notes: 'Includes 2 extra microfiber refills and reinforced steel spinner drum.',
    remarks: 'Freight Included • PlastoShip Escrow Protected • Rating: 4.7 ★ • Gala Brush & Household Corp (Ambernath, MH)',
    submittedAt: '2 days ago',
  },
];

export const INITIAL_DISTRIBUTOR_ORDERS: Order[] = [
  {
    id: 'PO-2026-88291',
    rfqId: 'RFQ-2026-0491',
    manufacturer: 'Nilkamal Moldings & Logistics Ltd',
    manufacturerName: 'Nilkamal Moldings & Logistics Ltd',
    distributor: 'Apex Polymers & Distributors LLP',
    distributorName: 'Apex Polymers & Distributors LLP',
    distributorCity: 'Bhiwandi, Thane',
    product: 'AeroSeal 4-Piece Airtight Modular Storage Set',
    productName: 'AeroSeal 4-Piece Airtight Modular Storage Set',
    category: 'Storage Containers',
    polymerGrade: 'STR-MOD-1200-4P',
    quantity: '2,500 Units',
    amount: 412500,
    totalAmount: 412500,
    unitPricePerKg: 165,
    orderStatus: 'In Transit',
    createdDate: '28 Aug 2026',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    paymentStatus: 'Escrow Held',
    trackingNumber: 'TRK-PL-9921820',
    estimatedDelivery: 'Tomorrow, 03:30 PM',
  },
  {
    id: 'PO-2026-88240',
    rfqId: 'RFQ-2026-0488',
    manufacturer: 'Milton Housewares & Appliances',
    manufacturerName: 'Milton Housewares & Appliances',
    distributor: 'Apex Polymers & Distributors LLP',
    distributorName: 'Apex Polymers & Distributors LLP',
    distributorCity: 'Bhiwandi, Thane',
    product: 'ThermaLock 3-Container Insulated Lunch Box',
    productName: 'ThermaLock 3-Container Insulated Lunch Box',
    category: 'Lunch Boxes',
    polymerGrade: 'LNC-TH-3C',
    quantity: '1,800 Units',
    amount: 864000,
    totalAmount: 864000,
    unitPricePerKg: 480,
    orderStatus: 'Dispatched',
    createdDate: '25 Aug 2026',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    paymentStatus: 'Escrow Held',
    trackingNumber: 'TRK-PL-9921815',
    estimatedDelivery: '03 Sep 2026',
  },
  {
    id: 'PO-2026-88195',
    rfqId: 'RFQ-2026-0460',
    manufacturer: 'Supreme Industries Polymer Works',
    manufacturerName: 'Supreme Industries Polymer Works',
    distributor: 'Apex Polymers & Distributors LLP',
    distributorName: 'Apex Polymers & Distributors LLP',
    distributorCity: 'Bhiwandi, Thane',
    product: 'DuraCrate Heavy-Duty Industrial Stacking Crate',
    productName: 'DuraCrate Heavy-Duty Industrial Stacking Crate',
    category: 'Storage Containers',
    polymerGrade: 'IND-CRT-6040',
    quantity: '1,200 Units',
    amount: 504000,
    totalAmount: 504000,
    unitPricePerKg: 420,
    orderStatus: 'Delivered',
    createdDate: '20 Aug 2026',
    dispatchHub: 'Bhiwandi Central Fulfillment Hub (MH-04)',
    paymentStatus: 'Paid to MFR',
    trackingNumber: 'TRK-PL-9921780',
    estimatedDelivery: 'Delivered on 24 Aug',
  },
  {
    id: 'PO-2026-88090',
    rfqId: 'RFQ-2026-0442',
    manufacturer: 'Cello World Plastics LLP',
    manufacturerName: 'Cello World Plastics LLP',
    distributor: 'Apex Polymers & Distributors LLP',
    distributorName: 'Apex Polymers & Distributors LLP',
    distributorCity: 'Pune Central Stockyard',
    product: 'ChefPro 3-Tier Revolving Spice Tower',
    productName: 'ChefPro 3-Tier Revolving Spice Tower',
    category: 'Kitchenware',
    polymerGrade: 'KTN-SP-3TR',
    quantity: '2,000 Units',
    amount: 570000,
    totalAmount: 570000,
    unitPricePerKg: 285,
    orderStatus: 'Confirmed',
    createdDate: '18 Aug 2026',
    dispatchHub: 'Pune Central Stockyard',
    paymentStatus: 'Escrow Held',
    trackingNumber: 'TRK-PL-9921750',
    estimatedDelivery: '05 Sep 2026',
  },
];

export const INITIAL_DISTRIBUTOR_TRANSACTIONS: DistributorTransaction[] = [
  {
    id: 'TXN-99812',
    date: '28 Aug 2026',
    referencePo: 'PO-2026-88291',
    type: 'Escrow Locked',
    amount: 412500,
    escrowStatus: 'In Escrow Vault',
    statusColor: 'emerald',
  },
  {
    id: 'TXN-99804',
    date: '25 Aug 2026',
    referencePo: 'PO-2026-88240',
    type: 'Credit Line Disbursed',
    amount: 864000,
    escrowStatus: 'Active 45-day Credit',
    statusColor: 'teal',
  },
  {
    id: 'TXN-99780',
    date: '24 Aug 2026',
    referencePo: 'PO-2026-88195',
    type: 'Settlement Released',
    amount: 504000,
    escrowStatus: 'Completed & Closed',
    statusColor: 'blue',
  },
  {
    id: 'TXN-99722',
    date: '18 Aug 2026',
    referencePo: 'PO-2026-88090',
    type: 'Advance Locked',
    amount: 570000,
    escrowStatus: 'In Escrow Vault',
    statusColor: 'emerald',
  },
];

export const INITIAL_DISTRIBUTOR_ESCROW_PAYMENTS: DistributorEscrowPayment[] = [
  {
    id: 'ESC-GJ-8092',
    orderId: 'PO-2026-88291',
    orderProduct: 'AeroSeal 4-Piece Airtight Modular Storage Set',
    manufacturerName: 'Nilkamal Moldings & Logistics Ltd',
    quantity: '2,500 Units',
    grossAmount: 412500,
    escrowDepositDate: '2026-08-28 14:22',
    escrowStatus: 'Funds in Escrow',
    paymentMethod: 'Razorpay B2B',
    utrNumber: 'UTR-HDFC-99210941',
  },
  {
    id: 'ESC-GJ-8071',
    orderId: 'PO-2026-88240',
    orderProduct: 'ThermaLock 3-Container Insulated Lunch Box',
    manufacturerName: 'Milton Housewares & Appliances',
    quantity: '1,800 Units',
    grossAmount: 864000,
    escrowDepositDate: '2026-08-25 11:15',
    escrowStatus: 'Funds in Escrow',
    paymentMethod: 'NEFT/RTGS',
    utrNumber: 'UTR-HDFC-99120482',
  },
  {
    id: 'ESC-GJ-8044',
    orderId: 'PO-2026-88195',
    orderProduct: 'DuraCrate Heavy-Duty Industrial Stacking Crate',
    manufacturerName: 'Supreme Industries Polymer Works',
    quantity: '1,200 Units',
    grossAmount: 504000,
    escrowDepositDate: '2026-08-20 09:40',
    escrowStatus: 'Released to Manufacturer',
    paymentMethod: 'Virtual Escrow Account',
    utrNumber: 'UTR-ICICI-88129031',
    releaseDate: '2026-08-24 16:30',
  },
];

export const INITIAL_DISTRIBUTOR_ADDRESSES: DistributorDeliveryAddress[] = [
  {
    id: 'ADDR-01',
    label: 'Primary Sourcing Hub (Bhiwandi)',
    contactName: 'Rajesh Singhania (Logistics Lead)',
    phone: '+91 98201 45890',
    address: 'Plot 42-A, Logistics Park Road, Bhiwandi',
    city: 'Thane, Maharashtra',
    pincode: '421302',
    isDefault: true,
  },
  {
    id: 'ADDR-02',
    label: 'Pune Central Stockyard Depot',
    contactName: 'Anil Deshmukh (Depot Manager)',
    phone: '+91 98201 45895',
    address: 'Shed 18, Chakan MIDC Phase 2',
    city: 'Pune, Maharashtra',
    pincode: '410501',
    isDefault: false,
  },
];

export const INITIAL_DISTRIBUTOR_ACTIVITIES = [
  {
    id: 'DST-ACT-01',
    title: 'RFQ Submitted: Bulk Sourcing 50L Storage Tubs',
    description: 'Tender broadcasted to 48 verified manufacturers for 3,000 units.',
    time: 'Yesterday at 04:30 PM',
    type: 'rfq',
    screen: 'dst_rfqs' as const,
    badge: 'Broadcasted',
  },
  {
    id: 'DST-ACT-02',
    title: 'Quotation Received from Supreme Industries',
    description: 'Quoted ₹372/unit for 3,000 units with freight included (Saving: ₹24,000).',
    time: 'Today at 10:15 AM',
    type: 'quote',
    screen: 'dst_quotations' as const,
    badge: 'New Quote',
  },
  {
    id: 'DST-ACT-03',
    title: 'Order Confirmed: ChefPro 3-Tier Spice Tower',
    description: 'Purchase order PO-2026-88090 accepted by Cello World Plastics LLP.',
    time: '18 Aug 2026',
    type: 'order',
    screen: 'dst_orders' as const,
    badge: 'PO Confirmed',
  },
  {
    id: 'DST-ACT-04',
    title: 'Consignment in Transit: AeroSeal Modular Sets',
    description: 'TRK-PL-9921820 passing Maharashtra State Expressway towards Bhiwandi.',
    time: 'Yesterday at 08:15 PM',
    type: 'tracking',
    screen: 'dst_tracking' as const,
    badge: 'In Transit',
  },
  {
    id: 'DST-ACT-05',
    title: 'Escrow Secured: PO-2026-88291',
    description: '₹4,12,500 deposited into PlastoShip Escrow Vault for Nilkamal Moldings.',
    time: '28 Aug 2026',
    type: 'payment',
    screen: 'dst_payments' as const,
    badge: 'Escrow Locked',
  },
];

